import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { CalendarDays, MapPin, Printer, RefreshCw, Search, Truck, UserRound, XCircle } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatusPill from '../components/StatusPill';
import DocumentLifecycle from '../components/DocumentLifecycle';
import Modal from '../components/Modal';
import DeliveryOrderPrintDocument from '../components/delivery-order/DeliveryOrderPrintDocument';
import CreateShipmentModal from '../components/shipment/CreateShipmentModal';
import { coreApi } from '../api/core';
import { useCoreList } from '../hooks/useCoreWorkspace';
import { dateLabel, dateTimeLabel, number, statusTone } from '../utils/erp';

const steps = ['Draft','Ready to Load','Loading','Loaded'];
const stepIndex = { DRAFT:0, READY_TO_LOAD:1, LOADING:2, LOADED:3, CANCELLED:0 };
const blankPlan = { deliveryDate:'', shippingAddress:'', carrier:'', vehicle:'', driver:'', dock:'', notes:'' };

export default function ApiDeliveryOrderPage(){
  const navigate=useNavigate();
  const loader=useCallback((scope)=>coreApi.deliveryOrders(scope),[]); const list=useCoreList(loader); const {scope}=list;
  const [selectedId,setSelectedId]=useState(''); const [detail,setDetail]=useState(null); const [plan,setPlan]=useState(blankPlan); const [query,setQuery]=useState(''); const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [cancelOpen,setCancelOpen]=useState(false); const [cancelReason,setCancelReason]=useState('');
  const [shipmentOpen,setShipmentOpen]=useState(false); const [shipmentLines,setShipmentLines]=useState([]); const [shipmentPlan,setShipmentPlan]=useState({scheduledAt:'',carrier:'',vehicle:'',driver:'',route:'',trackingNo:'',referenceNo:'',notes:''});
  const docs=useMemo(()=>list.rows.filter((r)=>`${r.documentNo} ${r.salesOrderNo} ${r.pickingOrderNo} ${r.customerName} ${r.status}`.toLowerCase().includes(query.toLowerCase())),[list.rows,query]);
  const load=useCallback(async(id)=>{if(!scope||!id)return;setBusy(`load:${id}`);try{const row=await coreApi.deliveryOrder(scope,id);setDetail(row);setPlan({deliveryDate:row.deliveryDate||'',shippingAddress:row.shippingAddress||'',carrier:row.carrier||'',vehicle:row.vehicle||'',driver:row.driver||'',dock:row.dock||'',notes:row.notes||''});}catch(e){setMessage(e.message)}finally{setBusy('')}},[scope?.entityCode,scope?.siteCode]);
  useEffect(()=>{const next=selectedId&&list.rows.some((r)=>r.id===selectedId)?selectedId:list.rows[0]?.id||'';if(next!==selectedId)setSelectedId(next);if(next)void load(next);else setDetail(null)},[list.rows,selectedId,load]);
  const refreshAll=async()=>{await list.refresh();if(selectedId)await load(selectedId)};
  const save=async()=>{if(!scope||!detail)return;if(!plan.shippingAddress.trim()){setMessage('Shipping address wajib diisi.');return}setBusy('save');setMessage('');try{await coreApi.updateDeliveryOrder(scope,detail.id,plan);setMessage(`${detail.documentNo} loading plan tersimpan.`);await refreshAll()}catch(e){setMessage(e.message)}finally{setBusy('')}};
  const transition=async(action,label)=>{if(!scope||!detail)return;setBusy(action);setMessage('');try{await coreApi.deliveryAction(scope,detail.id,action);setMessage(`${detail.documentNo} → ${label}`);await refreshAll()}catch(e){setMessage(e.message)}finally{setBusy('')}};
  const cancel=async()=>{if(!scope||!detail||!cancelReason.trim())return;setBusy('cancel');setMessage('');try{await coreApi.cancelDeliveryOrder(scope,detail.id,cancelReason.trim());setCancelOpen(false);setCancelReason('');setMessage(`${detail.documentNo} dibatalkan.`);await refreshAll()}catch(e){setMessage(e.message)}finally{setBusy('')}};
  const print=()=>{if(!detail)return;const old=document.title;const restore=()=>{document.title=old;window.removeEventListener('afterprint',restore)};document.title=`Delivery Order ${detail.documentNo}`;window.addEventListener('afterprint',restore);window.print()};
  const openShipment=()=>{if(!detail)return;const rows=(detail.lines||[]).filter((line)=>Number(line.availableForShipmentQty||0)>0.000001).map((line)=>({deliveryLineId:line.id,sku:line.sku,itemName:line.itemName,uom:line.uom,loadedQty:Number(line.qty||0),allocatedQty:Number(line.shipmentAllocatedQty||0),max:Number(line.availableForShipmentQty||0),qty:Number(line.availableForShipmentQty||0)}));setShipmentLines(rows);setShipmentPlan({scheduledAt:'',carrier:detail.carrier||'',vehicle:detail.vehicle||'',driver:detail.driver||'',route:'',trackingNo:'',referenceNo:detail.documentNo||'',notes:detail.notes||''});setShipmentOpen(true)};
  const createShipment=async()=>{if(!scope||!detail)return;const invalid=shipmentLines.find((line)=>Number(line.qty)<0||Number(line.qty)>Number(line.max)+0.000001);if(invalid){setMessage(`Shipment Qty ${invalid.sku} tidak boleh melebihi ${number(invalid.max)} ${invalid.uom}.`);return}const lines=shipmentLines.filter((line)=>Number(line.qty)>0).map((line)=>({deliveryLineId:line.deliveryLineId,qty:Number(line.qty)}));if(!lines.length){setMessage('Pilih minimal satu qty untuk Shipment.');return}setBusy('shipment');setMessage('');try{const result=await coreApi.createShipment(scope,detail.id,{...shipmentPlan,lines});setShipmentOpen(false);setMessage(`${result.documentNo} berhasil dibuat.`);await refreshAll();navigate('/transactions/distribution/shipment')}catch(e){setMessage(e.message)}finally{setBusy('')}};
  const shipmentAvailable=detail?.status==='LOADED'&&(detail?.lines||[]).some((line)=>Number(line.availableForShipmentQty||0)>0.000001);
  const hasShipmentAllocation=(detail?.lines||[]).some((line)=>Number(line.shipmentAllocatedQty||0)>0.000001);
  const canCancelDelivery=detail&&['DRAFT','READY_TO_LOAD','LOADING','LOADED'].includes(detail.status)&&!hasShipmentAllocation;
  const editable=detail&&['DRAFT','READY_TO_LOAD'].includes(detail.status);
  if(!detail&&!list.loading&&list.rows.length===0)return <><PageHeader eyebrow="Transaction / Distribution / Delivery Order" title="Delivery Order · PostgreSQL" description="Delivery Order dibuat dari completed Picking dan mengalokasikan picked quantity tanpa mengubah On Hand."/><div className="surface-card empty-state-large">Belum ada Delivery Order. Selesaikan Picking lalu pilih <strong>Create Delivery Order</strong>.</div></>;
  return <><PageHeader eyebrow="Transaction / Distribution / Delivery Order" title="Delivery Order · PostgreSQL" description="Picked qty → Delivery Order → loading. Stock fisik belum keluar sampai Shipment D3-C."/>{message&&<div className="v10-inline-note"><strong>Delivery Order</strong><span>{message}</span></div>}{list.error&&<div className="v10-inline-note warning"><strong>API</strong><span>{list.error}</span></div>}<div className="document-layout">
    <aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari DO / SO / PKO / customer..."/></label><button className="icon-btn" onClick={list.refresh}><RefreshCw size={14}/></button></div><div className="document-list">{docs.map((row)=><button key={row.id} className={`document-row ${row.id===selectedId?'active':''}`} onClick={()=>{setSelectedId(row.id);void load(row.id)}}><div className="document-row__top"><strong>{row.documentNo}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{row.salesOrderNo} · {row.customerName}</span><div className="document-row__meta"><small>{dateLabel(row.deliveryDate)}</small><strong>{number(row.qty)} qty</strong></div></button>)}</div></aside>
    <section className="document-workspace">{!detail?<div className="surface-card empty-state-large">Memuat Delivery Order...</div>:<><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">DO · {detail.warehouse?.code} · {detail.pickingOrder?.documentNo}</div><h2>{detail.documentNo}</h2><p>{detail.customer?.name}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(detail.status)}>{detail.status}</StatusPill><div className="action-row"><button className="btn" disabled={!!busy} onClick={print}><Printer size={14}/> Print</button>{editable&&<button className="btn" disabled={!!busy} onClick={save}>Save Plan</button>}{detail.status==='DRAFT'&&<button className="btn btn-primary" disabled={!!busy} onClick={()=>transition('release','READY TO LOAD')}>Release to Loading</button>}{detail.status==='READY_TO_LOAD'&&<button className="btn btn-primary" disabled={!!busy} onClick={()=>transition('start-loading','LOADING')}>Start Loading</button>}{detail.status==='LOADING'&&<button className="btn btn-primary" disabled={!!busy} onClick={()=>transition('complete-loading','LOADED')}>Complete Loading</button>}{shipmentAvailable&&<button className="btn btn-primary" disabled={!!busy} onClick={openShipment}><Truck size={14}/> Create Shipment</button>}{canCancelDelivery&&<button className="btn" disabled={!!busy} onClick={()=>setCancelOpen(true)}><XCircle size={14}/> Cancel</button>}</div></div></div><div className="doc-summary-grid"><div><CalendarDays size={15}/><span>Delivery date</span><strong>{dateLabel(detail.deliveryDate)}</strong></div><div><UserRound size={15}/><span>Driver</span><strong>{detail.driver||'Unassigned'}</strong></div><div><MapPin size={15}/><span>Dock</span><strong>{detail.dock||'Unassigned'}</strong></div><div><Truck size={15}/><span>Vehicle</span><strong>{detail.vehicle||'Unassigned'}</strong></div></div></div>
    <DocumentLifecycle steps={steps} currentIndex={stepIndex[detail.status]??0} label={detail.status}/>{detail.status==='LOADED'&&<div className="v10-inline-note"><strong>Loading selesai</strong><span>Delivery Order siap menjadi sumber Shipment di D3-C. On Hand dan Reserved belum berubah.</span></div>}
    <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Delivery Lines</h3><p>Qty berasal dari completed Picking dan bisa merupakan partial allocation.</p></div><span>{detail.lines?.length||0} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>Loaded Qty</th><th>Shipment Allocated</th><th>Available for Shipment</th><th>Pick Location</th><th>Lot</th></tr></thead><tbody>{(detail.lines||[]).map((line)=><tr key={line.id}><td><strong>{line.sku}</strong><small>{line.itemName}</small></td><td>{number(line.qty)} {line.uom}</td><td>{number(line.shipmentAllocatedQty||0)} {line.uom}</td><td>{number(line.availableForShipmentQty||0)} {line.uom}</td><td>{line.location||'-'}</td><td>{line.lotNo||'-'}</td></tr>)}</tbody></table></div></section>
    <aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Delivery & Loading Plan</h3><p>Dapat diubah sebelum proses loading dimulai.</p></div></header><div className="inline-form"><label className="field"><span>Delivery Date</span><input type="date" disabled={!editable} value={plan.deliveryDate} onChange={(e)=>setPlan({...plan,deliveryDate:e.target.value})}/></label><label className="field"><span>Shipping Address</span><textarea rows="3" disabled={!editable} value={plan.shippingAddress} onChange={(e)=>setPlan({...plan,shippingAddress:e.target.value})}/></label><label className="field"><span>Carrier</span><input disabled={!editable} value={plan.carrier} onChange={(e)=>setPlan({...plan,carrier:e.target.value})}/></label><label className="field"><span>Vehicle</span><input disabled={!editable} value={plan.vehicle} onChange={(e)=>setPlan({...plan,vehicle:e.target.value})}/></label><label className="field"><span>Driver</span><input disabled={!editable} value={plan.driver} onChange={(e)=>setPlan({...plan,driver:e.target.value})}/></label><label className="field"><span>Dock</span><input disabled={!editable} value={plan.dock} onChange={(e)=>setPlan({...plan,dock:e.target.value})}/></label><label className="field"><span>Notes</span><textarea rows="2" disabled={!editable} value={plan.notes} onChange={(e)=>setPlan({...plan,notes:e.target.value})}/></label></div></section><section className="surface-card document-section compact-info"><header><div><h3>Traceability</h3><p>Source document chain.</p></div></header><div className="related-row static"><div><span>Sales Order</span><strong>{detail.salesOrder?.documentNo}</strong></div></div><div className="related-row static"><div><span>Picking Order</span><strong>{detail.pickingOrder?.documentNo}</strong></div></div><div className="related-row static"><div><span>Shipment</span><strong>{detail.status==='LOADED'?'Ready for D3-C':'Not ready'}</strong></div></div></section></aside></div></>}
    </section></div><Modal open={cancelOpen} onClose={()=>setCancelOpen(false)} title={`Cancel ${detail?.documentNo||''}`} subtitle="Allocation qty akan kembali tersedia untuk Delivery Order lain." footer={<><button className="btn" onClick={()=>setCancelOpen(false)}>Kembali</button><button className="btn btn-primary" disabled={!cancelReason.trim()||!!busy} onClick={cancel}>Cancel Delivery Order</button></>}><label className="field"><span>Alasan pembatalan</span><textarea rows="4" value={cancelReason} onChange={(e)=>setCancelReason(e.target.value)} placeholder="Wajib diisi untuk audit trail"/></label></Modal><CreateShipmentModal open={shipmentOpen} onClose={()=>setShipmentOpen(false)} detail={detail} lines={shipmentLines} setLines={setShipmentLines} plan={shipmentPlan} setPlan={setShipmentPlan} onCreate={createShipment} busy={busy}/>{detail&&<DeliveryOrderPrintDocument detail={detail}/>}</>;
}
