import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarClock, FileCheck2, MapPin, PackageCheck, Printer, RefreshCw, Route, Truck, UserRound, XCircle } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatusPill from '../components/StatusPill';
import DocumentLifecycle from '../components/DocumentLifecycle';
import Modal from '../components/Modal';
import ShipmentPrintDocument from '../components/shipment/ShipmentPrintDocument';
import { coreApi } from '../api/core';
import { useCoreList } from '../hooks/useCoreWorkspace';
import { dateTimeLabel, money, number, statusTone } from '../utils/erp';

const blankPlan = { scheduledAt:'', carrier:'', vehicle:'', driver:'', route:'', trackingNo:'', referenceNo:'', notes:'' };
const blankPod = { recipient:'', receivedAt:'', reference:'', notes:'' };
const steps = ['Planned','Dispatched','Delivered'];
const stepIndex = { PLANNED:0, DISPATCHED:1, DELIVERED:2, CANCELLED:0 };

export default function ApiShipmentPage(){
  const loader=useCallback((scope)=>coreApi.shipments(scope),[]);
  const list=useCoreList(loader); const {scope}=list;
  const [selectedId,setSelectedId]=useState(''); const [detail,setDetail]=useState(null); const [query,setQuery]=useState('');
  const [plan,setPlan]=useState(blankPlan); const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [actionError,setActionError]=useState('');
  const [podOpen,setPodOpen]=useState(false); const [pod,setPod]=useState(blankPod); const [cancelOpen,setCancelOpen]=useState(false); const [cancelReason,setCancelReason]=useState('');
  const docs=useMemo(()=>list.rows.filter((r)=>`${r.documentNo} ${r.deliveryOrderNo} ${r.salesOrderNo} ${r.customerName} ${r.status} ${r.trackingNo||''}`.toLowerCase().includes(query.toLowerCase())),[list.rows,query]);
  const load=useCallback(async(id)=>{if(!scope||!id)return;setBusy(`load:${id}`);try{const row=await coreApi.shipment(scope,id);setDetail(row);setPlan({scheduledAt:(row.scheduledAt||'').slice(0,16),carrier:row.carrier||'',vehicle:row.vehicle||'',driver:row.driver||'',route:row.route||'',trackingNo:row.trackingNo||'',referenceNo:row.referenceNo||'',notes:row.notes||''});}catch(e){setMessage(e.message)}finally{setBusy('')}},[scope?.entityCode,scope?.siteCode]);
  useEffect(()=>{const next=selectedId&&list.rows.some((r)=>r.id===selectedId)?selectedId:list.rows[0]?.id||'';if(next!==selectedId)setSelectedId(next);if(next)void load(next);else setDetail(null)},[list.rows,selectedId,load]);
  const refreshAll=async()=>{await list.refresh();if(selectedId)await load(selectedId)};
  const save=async()=>{if(!scope||!detail)return;setBusy('save');setMessage('');try{await coreApi.updateShipment(scope,detail.id,plan);setMessage(`${detail.documentNo} dispatch plan tersimpan.`);await refreshAll()}catch(e){setMessage(e.message)}finally{setBusy('')}};
  // Save Plan is a separate command. Dispatch must not issue another PATCH or silently discard unsaved edits.
  const dispatchPlanDirty=useMemo(()=>!!detail&&Object.entries(plan).some(([key,value])=>String(value??'')!==String(key==='scheduledAt'?(detail.scheduledAt||'').slice(0,16):(detail[key]||''))),[plan,detail]);
  const dispatch=async()=>{
    if(!scope||!detail)return;
    if(dispatchPlanDirty){const msg='Dispatch Plan berubah. Klik Save Plan dahulu, lalu Dispatch.';setActionError(msg);setMessage(msg);return;}
    if(!plan.vehicle.trim()||!plan.driver.trim()){const msg='Vehicle dan Driver wajib diisi sebelum Dispatch.';setActionError(msg);setMessage(msg);return;}
    setBusy('dispatch');setMessage('');setActionError('');
    try{const result=await coreApi.dispatchShipment(scope,detail.id);setMessage(`${detail.documentNo} → DISPATCHED · stock issue + COGS posted.`);await refreshAll();return result}
    catch(e){const msg=e?.message||'Dispatch gagal. Lihat Network → Response.';setMessage(msg);setActionError(msg)}
    finally{setBusy('')}
  };
  const deliver=async()=>{if(!scope||!detail)return;if(!pod.recipient.trim()||!pod.reference.trim()){setMessage('POD Recipient dan POD Reference wajib diisi.');return}setBusy('deliver');setMessage('');try{await coreApi.deliverShipment(scope,detail.id,pod);setPodOpen(false);setPod(blankPod);setMessage(`${detail.documentNo} → DELIVERED + POD tercatat.`);await refreshAll()}catch(e){setMessage(e.message)}finally{setBusy('')}};
  const cancel=async()=>{if(!scope||!detail||!cancelReason.trim())return;setBusy('cancel');setMessage('');try{await coreApi.cancelShipment(scope,detail.id,cancelReason.trim());setCancelOpen(false);setCancelReason('');setMessage(`${detail.documentNo} dibatalkan. Allocation kembali tersedia untuk Shipment lain.`);await refreshAll()}catch(e){setMessage(e.message)}finally{setBusy('')}};
  const print=()=>{if(!detail)return;const old=document.title;const restore=()=>{document.title=old;window.removeEventListener('afterprint',restore)};document.title=`Shipment ${detail.documentNo}`;window.addEventListener('afterprint',restore);window.print()};
  const editable=detail?.status==='PLANNED';
  if(!detail&&!list.loading&&list.rows.length===0)return <><PageHeader eyebrow="Transaction / Distribution / Shipment" title="Shipment & POD · PostgreSQL" description="Shipment dibuat dari LOADED Delivery Order. Dispatch adalah titik physical stock issue."/><div className="surface-card empty-state-large">Belum ada Shipment. Complete Loading pada Delivery Order lalu pilih <strong>Create Shipment</strong>.</div></>;
  return <><PageHeader eyebrow="Transaction / Distribution / Shipment" title="Shipment & POD · PostgreSQL" description="Planned shipment → Dispatch stock issue + COGS → Proof of Delivery."/>
    {message&&<div className="v10-inline-note"><strong>Shipment</strong><span>{message}</span></div>}{list.error&&<div className="v10-inline-note warning"><strong>API</strong><span>{list.error}</span></div>}
    <div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari SHP / DO / SO / customer / tracking..."/></label><button className="icon-btn" onClick={list.refresh}><RefreshCw size={14}/></button></div><div className="document-list">{docs.map((row)=><button key={row.id} className={`document-row ${row.id===selectedId?'active':''}`} onClick={()=>{setSelectedId(row.id);void load(row.id)}}><div className="document-row__top"><strong>{row.documentNo}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{row.deliveryOrderNo||'Legacy'} · {row.customerName}</span><div className="document-row__meta"><small>{dateTimeLabel(row.dispatchedAt||row.scheduledAt||row.createdAt)}</small><strong>{number(row.qty)} qty</strong></div></button>)}</div></aside>
    <section className="document-workspace">{!detail?<div className="surface-card empty-state-large">Memuat Shipment...</div>:<><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">SHP · {detail.warehouse?.code} · {detail.deliveryOrder?.documentNo||'LEGACY'}</div><h2>{detail.documentNo}</h2><p>{detail.customer?.name}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(detail.status)}>{detail.status}</StatusPill><div className="action-row"><button className="btn" disabled={!!busy} onClick={print}><Printer size={14}/> Print</button>{editable&&<button className="btn" disabled={!!busy} onClick={save}>Save Plan</button>}{detail.status==='PLANNED'&&<button className="btn btn-primary" disabled={!!busy} onClick={dispatch}><Truck size={14}/> Dispatch</button>}{detail.status==='DISPATCHED'&&<button className="btn btn-primary" disabled={!!busy} onClick={()=>setPodOpen(true)}><FileCheck2 size={14}/> Confirm Delivery + POD</button>}{detail.status==='PLANNED'&&<button className="btn" disabled={!!busy} onClick={()=>setCancelOpen(true)}><XCircle size={14}/> Cancel</button>}</div>{actionError&&<div role="alert" className="v10-inline-note warning"><strong>Dispatch</strong><span>{actionError}</span></div>}</div></div>
    <div className="doc-summary-grid"><div><CalendarClock size={15}/><span>Scheduled</span><strong>{dateTimeLabel(detail.scheduledAt)}</strong></div><div><UserRound size={15}/><span>Driver</span><strong>{detail.driver||'Unassigned'}</strong></div><div><Route size={15}/><span>Route</span><strong>{detail.route||'Unassigned'}</strong></div><div><Truck size={15}/><span>Vehicle</span><strong>{detail.vehicle||'Unassigned'}</strong></div></div></div>
    <DocumentLifecycle steps={steps} currentIndex={stepIndex[detail.status]??0} label={detail.status}/>
    {detail.status==='PLANNED'&&<div className="v10-inline-note"><strong>Belum ada stock movement</strong><span>Shipment masih planning. On Hand dan Reserved baru berubah atomically saat Dispatch.</span></div>}
    {detail.status==='DISPATCHED'&&<div className="v10-inline-note"><strong>Physical issue posted</strong><span>On Hand dan Reserved sudah dikurangi. Menunggu Proof of Delivery.</span></div>}
    <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Cargo Manifest</h3><p>Qty Shipment berasal dari loaded Delivery Order dan dapat partial.</p></div><span>{detail.lines?.length||0} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>Qty</th><th>Location</th><th>Lot</th><th>Unit Cost</th><th>COGS</th></tr></thead><tbody>{(detail.lines||[]).map((line)=><tr key={line.id}><td><strong>{line.sku}</strong><small>{line.itemName}</small></td><td>{number(line.qty)} {line.uom}</td><td>{line.location||'-'}</td><td>{line.lotNo||'-'}</td><td>{Number(line.unitCost)>0?money(line.unitCost):'-'}</td><td>{Number(line.cogs)>0?money(line.cogs):'-'}</td></tr>)}</tbody></table></div></section>
    <aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Dispatch Plan</h3><p>Editable hanya sebelum Dispatch.</p></div></header><div className="inline-form"><label className="field"><span>Scheduled At</span><input type="datetime-local" disabled={!editable} value={plan.scheduledAt} onChange={(e)=>setPlan({...plan,scheduledAt:e.target.value})}/></label><label className="field"><span>Carrier</span><input disabled={!editable} value={plan.carrier} onChange={(e)=>setPlan({...plan,carrier:e.target.value})}/></label><label className="field"><span>Vehicle *</span><input disabled={!editable} value={plan.vehicle} onChange={(e)=>setPlan({...plan,vehicle:e.target.value})}/></label><label className="field"><span>Driver *</span><input disabled={!editable} value={plan.driver} onChange={(e)=>setPlan({...plan,driver:e.target.value})}/></label><label className="field"><span>Route</span><input disabled={!editable} value={plan.route} onChange={(e)=>setPlan({...plan,route:e.target.value})}/></label><label className="field"><span>Tracking No.</span><input disabled={!editable} value={plan.trackingNo} onChange={(e)=>setPlan({...plan,trackingNo:e.target.value})}/></label><label className="field"><span>Reference</span><input disabled={!editable} value={plan.referenceNo} onChange={(e)=>setPlan({...plan,referenceNo:e.target.value})}/></label><label className="field"><span>Notes</span><textarea rows="2" disabled={!editable} value={plan.notes} onChange={(e)=>setPlan({...plan,notes:e.target.value})}/></label></div></section>
    <section className="surface-card document-section compact-info"><header><div><h3>Traceability & POD</h3><p>End-to-end fulfillment chain.</p></div></header><div className="related-row static"><div><span>Sales Order</span><strong>{detail.salesOrder?.documentNo}</strong></div></div><div className="related-row static"><div><span>Delivery Order</span><strong>{detail.deliveryOrder?.documentNo||'Legacy direct shipment'}</strong></div></div><div className="related-row static"><div><span>COGS Journal</span><strong>{detail.cogsJournal?.documentNo||'Posted on dispatch'}</strong></div></div><div className="related-row static"><div><span>POD Recipient</span><strong>{detail.pod?.recipient||'Waiting'}</strong></div></div><div className="related-row static"><div><span>POD Reference</span><strong>{detail.pod?.reference||'Waiting'}</strong></div></div><div className="related-row static"><div><span>POD Received</span><strong>{dateTimeLabel(detail.pod?.receivedAt)}</strong></div></div></section></aside></div></>}</section></div>
    <Modal open={podOpen} onClose={()=>setPodOpen(false)} title={`Proof of Delivery · ${detail?.documentNo||''}`} subtitle="Konfirmasi ini tidak mengubah stock lagi. Stock sudah keluar saat Dispatch." footer={<><button className="btn" onClick={()=>setPodOpen(false)}>Kembali</button><button className="btn btn-primary" disabled={!!busy||!pod.recipient.trim()||!pod.reference.trim()} onClick={deliver}>Confirm Delivered</button></>}><div className="inline-form"><label className="field"><span>Recipient *</span><input value={pod.recipient} onChange={(e)=>setPod({...pod,recipient:e.target.value})}/></label><label className="field"><span>Received At</span><input type="datetime-local" value={pod.receivedAt} onChange={(e)=>setPod({...pod,receivedAt:e.target.value})}/></label><label className="field"><span>POD Reference *</span><input value={pod.reference} onChange={(e)=>setPod({...pod,reference:e.target.value})} placeholder="Signed DO / photo / receiver reference"/></label><label className="field"><span>Notes</span><textarea rows="3" value={pod.notes} onChange={(e)=>setPod({...pod,notes:e.target.value})}/></label></div></Modal>
    <Modal open={cancelOpen} onClose={()=>setCancelOpen(false)} title={`Cancel ${detail?.documentNo||''}`} subtitle="Hanya Shipment PLANNED yang bisa dibatalkan. Tidak ada stock movement." footer={<><button className="btn" onClick={()=>setCancelOpen(false)}>Kembali</button><button className="btn btn-primary" disabled={!!busy||!cancelReason.trim()} onClick={cancel}>Cancel Shipment</button></>}><label className="field"><span>Alasan pembatalan</span><textarea rows="4" value={cancelReason} onChange={(e)=>setCancelReason(e.target.value)}/></label></Modal>
    {detail&&<ShipmentPrintDocument detail={detail}/>}</>;
}
