import React, { useCallback, useMemo, useState } from 'react';
import { ArrowRightLeft, Boxes, Database, History, Plus, RefreshCw, Warehouse } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import SectionCard from '../components/SectionCard';
import StatCard from '../components/StatCard';
import DataTable from '../components/DataTable';
import StatusPill from '../components/StatusPill';
import Modal from '../components/Modal';
import { coreApi } from '../api/core';
import { useCoreBootstrap, useCoreList } from '../hooks/useCoreWorkspace';
import { dateTimeLabel, money, number, statusTone } from '../utils/erp';

export default function ApiWarehousePage(){
  const invLoader=useCallback(s=>coreApi.inventory(s),[]),movLoader=useCallback(s=>coreApi.movements(s),[]),trLoader=useCallback(s=>coreApi.transfers(s),[]);
  const inv=useCoreList(invLoader),mov=useCoreList(movLoader),tr=useCoreList(trLoader),masters=useCoreBootstrap(); const {scope}=inv;
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(''),[message,setMessage]=useState(''); const [form,setForm]=useState({sourceWarehouseCode:'',destinationWarehouseCode:'',transferDate:new Date().toISOString().slice(0,10),lines:[{sku:'',qty:1}]});
  React.useEffect(()=>{if(open){const wh=masters.data?.warehouses||[];setForm({sourceWarehouseCode:wh[0]?.code||'',destinationWarehouseCode:wh[1]?.code||'',transferDate:new Date().toISOString().slice(0,10),lines:[{sku:masters.data?.items?.[0]?.sku||'',qty:1}]})}},[open,masters.data]);
  const refreshAll=async()=>Promise.all([inv.refresh(),mov.refresh(),tr.refresh()]);
  const create=async()=>{if(!scope)return;setBusy('create');try{const res=await coreApi.createTransfer(scope,{siteCode:scope.siteCode,sourceWarehouseCode:form.sourceWarehouseCode,destinationWarehouseCode:form.destinationWarehouseCode,transferDate:form.transferDate,lines:form.lines.map(l=>({sku:l.sku,qty:Number(l.qty)}))});setMessage(`${res.documentNo} created`);setOpen(false);await refreshAll()}catch(e){setMessage(e.message)}finally{setBusy('')}};
  const action=async(row,act)=>{if(!scope)return;setBusy(`${row.id}:${act}`);try{const res=await coreApi.transferAction(scope,row.id,act);setMessage(`${res.documentNo} → ${res.status}`);await refreshAll()}catch(e){setMessage(e.message)}finally{setBusy('')}};
  const onHand=inv.rows.reduce((s,r)=>s+Number(r.onHand||0),0),reserved=inv.rows.reduce((s,r)=>s+Number(r.reserved||0),0),inbound=inv.rows.reduce((s,r)=>s+Number(r.inbound||0),0),value=inv.rows.reduce((s,r)=>s+Number(r.inventoryValue||0),0);
  const invCols=[{key:'warehouseCode',label:'Warehouse',render:v=><strong>{v}</strong>},{key:'sku',label:'SKU'},{key:'itemName',label:'Item'},{key:'onHand',label:'On Hand',render:v=>number(v)},{key:'reserved',label:'Reserved',render:v=>number(v)},{key:'inbound',label:'Inbound',render:v=>number(v)},{key:'available',label:'Available',render:v=><strong>{number(v)}</strong>},{key:'averageCost',label:'Avg Cost',render:v=>money(v)},{key:'inventoryValue',label:'Value',render:v=>money(v)},{key:'rowVersion',label:'Version'}];
  const trCols=useMemo(()=>[{key:'documentNo',label:'Transfer',render:v=><strong>{v}</strong>},{key:'sourceWarehouseCode',label:'Source'},{key:'destinationWarehouseCode',label:'Destination'},{key:'qty',label:'Qty',render:v=>number(v)},{key:'shippedQty',label:'Shipped',render:v=>number(v)},{key:'receivedQty',label:'Received',render:v=>number(v)},{key:'status',label:'Status',render:v=><StatusPill tone={statusTone(v)}>{v}</StatusPill>},{key:'action',label:'Action',render:(_,r)=><div className="action-row v11-row-actions">{r.status==='DRAFT'&&<button className="btn btn-sm btn-primary" disabled={!!busy} onClick={()=>action(r,'release')}>Release</button>}{r.status==='IN_TRANSIT'&&<button className="btn btn-sm btn-primary" disabled={!!busy} onClick={()=>action(r,'receive')}>Receive</button>}</div>}],[busy,scope]);
  const movCols=[{key:'occurredAt',label:'Time',render:v=>dateTimeLabel(v)},{key:'type',label:'Movement'},{key:'warehouseCode',label:'Warehouse'},{key:'sku',label:'SKU'},{key:'qty',label:'Qty',render:v=><strong className={Number(v)<0?'negative-number':'positive-number'}>{Number(v)>0?'+':''}{number(v)}</strong>},{key:'unitCost',label:'Unit Cost',render:v=>money(v)},{key:'value',label:'Value',render:v=>money(v)},{key:'referenceId',label:'Reference'}];
  return <>
    <PageHeader eyebrow="Production Core / Warehouse" title="Inventory Ledger · PostgreSQL" description="Warehouse source of truth sekarang menggunakan inventory balance dengan row_version, physical stock movement ledger, dan atomic inter-site transfer." actionLabel="Transfer Baru" onAction={()=>setOpen(true)}/>
    <div className="v11-mode-banner"><Database size={16}/><div><strong>ROW LOCK + OPTIMISTIC VERSION</strong><span>{scope?`${scope.entityCode}${scope.siteCode?` · ${scope.siteCode}`:' · All Sites'}`:'Select legal entity'} · transfer release memvalidasi Available = On Hand − Reserved.</span></div><button className="btn btn-sm" onClick={refreshAll} disabled={inv.loading}><RefreshCw size={13}/> Refresh</button></div>
    {message&&<div className="v10-inline-note"><strong>Warehouse command</strong><span>{message}</span></div>}{inv.error&&<div className="v10-inline-note warning"><strong>API unavailable</strong><span>{inv.error}</span></div>}
    <div className="stats-grid"><StatCard title="On Hand" value={number(onHand)} hint="physical balance" icon={Warehouse}/><StatCard title="Reserved" value={number(reserved)} hint="sales allocation" icon={Boxes}/><StatCard title="Inbound" value={number(inbound)} hint="waiting put-away" icon={RefreshCw}/><StatCard title="Inventory Value" value={money(value)} hint="moving average" icon={Database}/></div>
    <SectionCard title="Inventory Balance" subtitle="Setiap mutation memakai database transaction dan row_version."><DataTable rows={inv.rows} columns={invCols} emptyText={inv.loading?'Memuat PostgreSQL...':'Belum ada inventory.'}/></SectionCard>
    <SectionCard title="Inter-Site Stock Transfer" subtitle="Draft → In Transit → Received. Carrying cost dipertahankan di destination."><DataTable rows={tr.rows} columns={trCols} emptyText="Belum ada transfer PostgreSQL."/></SectionCard>
    <SectionCard title="Immutable-style Stock Movement Ledger" subtitle="Shipment, receiving, put-away, transfer out/in tercatat sebagai physical movement."><DataTable rows={mov.rows} columns={movCols} emptyText="Belum ada stock movement."/></SectionCard>
    <Modal open={open} onClose={()=>setOpen(false)} title="Create Production Stock Transfer" subtitle="Hanya warehouse dalam legal entity yang sama." wide footer={<><button className="btn" onClick={()=>setOpen(false)}>Batal</button><button className="btn btn-primary" disabled={busy==='create'||!form.sourceWarehouseCode||!form.destinationWarehouseCode||form.sourceWarehouseCode===form.destinationWarehouseCode} onClick={create}>Create Transfer</button></>}>
      <div className="form-grid"><label className="field"><span>Source Warehouse</span><select value={form.sourceWarehouseCode} onChange={e=>setForm({...form,sourceWarehouseCode:e.target.value})}>{(masters.data?.warehouses||[]).map(r=><option key={r.id} value={r.code}>{r.code} · {r.name}</option>)}</select></label><label className="field"><span>Destination Warehouse</span><select value={form.destinationWarehouseCode} onChange={e=>setForm({...form,destinationWarehouseCode:e.target.value})}>{(masters.data?.warehouses||[]).map(r=><option key={r.id} value={r.code}>{r.code} · {r.name}</option>)}</select></label><label className="field"><span>Transfer Date</span><input type="date" value={form.transferDate} onChange={e=>setForm({...form,transferDate:e.target.value})}/></label></div>
      <div className="modal-line-head"><div><strong>Transfer Lines</strong><small>Release akan row-lock source inventory.</small></div><button className="btn btn-sm" onClick={()=>setForm({...form,lines:[...form.lines,{sku:masters.data?.items?.[0]?.sku||'',qty:1}]})}><Plus size={13}/> Item</button></div>
      <div className="line-editor">{form.lines.map((line,i)=><div className="line-editor-row" key={i}><label className="field"><span>SKU</span><select value={line.sku} onChange={e=>setForm({...form,lines:form.lines.map((x,j)=>j===i?{...x,sku:e.target.value}:x)})}>{(masters.data?.items||[]).map(r=><option key={r.id} value={r.sku}>{r.sku} · {r.name}</option>)}</select></label><label className="field"><span>Qty</span><input type="number" min="1" value={line.qty} onChange={e=>setForm({...form,lines:form.lines.map((x,j)=>j===i?{...x,qty:e.target.value}:x)})}/></label></div>)}</div>
    </Modal>
  </>;
}
