import React, { useMemo, useState } from 'react';
import { Building2, CheckCircle2, CircleDollarSign, Layers3, LockKeyhole, RefreshCw, Scale, WandSparkles } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatCard from '../components/StatCard';
import SectionCard from '../components/SectionCard';
import DataTable from '../components/DataTable';
import StatusPill from '../components/StatusPill';
import { useERPData } from '../context/ERPDataContext';
import { dateTimeLabel, money, statusTone } from '../utils/erp';

export default function ConsolidationPage(){
  const {rawData,scope,setGroupScope,getConsolidationPreview,prepareConsolidation,postConsolidation}=useERPData();
  const [year,setYear]=useState(2026); const [month,setMonth]=useState(9);
  React.useEffect(()=>{if(scope.mode!=='GROUP')setGroupScope(scope.groupId)},[]);
  const preview=getConsolidationPreview({year,month,groupId:scope.groupId});
  const group=rawData.consolidationGroups.find((g)=>g.id===scope.groupId);
  const run=rawData.consolidationRuns.find((r)=>r.groupId===scope.groupId&&Number(r.year)===Number(year)&&Number(r.month)===Number(month)&&r.status!=='Cancelled');
  const icRows=useMemo(()=>rawData.intercompanyTransactions.filter((r)=>r.groupId===scope.groupId&&Number(r.date?.slice(0,4))===Number(year)&&Number(r.date?.slice(5,7))===Number(month)&&['Posted','Settled'].includes(r.status)).map((r)=>({id:r.id,type:r.type,pair:`${rawData.legalEntities.find((e)=>e.id===r.fromEntityId)?.code} → ${rawData.legalEntities.find((e)=>e.id===r.toEntityId)?.code}`,amount:r.amount,outstanding:r.outstandingAmount,unrealized:r.unrealizedProfit||0,eliminationStatus:r.eliminationStatus})),[rawData,year,month,scope.groupId]);
  const entityRows=preview.entityResults.map((row)=>({...row,revenueLabel:money(row.revenue),expenseLabel:money(row.expense),netLabel:money(row.netIncome),blockerCount:Object.values(row.blockers).reduce((s,v)=>s+Number(v||0),0)}));
  const prepare=()=>prepareConsolidation({year,month,groupId:scope.groupId});
  return <>
    <PageHeader eyebrow="Enterprise / Group Finance" title="Consolidation & Eliminations" description="Entity close readiness, intercompany elimination, due-to/due-from elimination, unrealized inventory profit, dan consolidated financial result." actionLabel={!run?'Prepare Consolidation':run.status==='Prepared'&&preview.allEntitiesClosed?'Post Consolidation':undefined} onAction={!run?prepare:run?.status==='Prepared'?()=>postConsolidation(run.id):undefined}/>
    <div className="filter-strip"><label className="field compact-field"><span>Fiscal Year</span><select value={year} onChange={(e)=>setYear(Number(e.target.value))}><option value={2026}>2026</option><option value={2027}>2027</option></select></label><label className="field compact-field"><span>Period</span><select value={month} onChange={(e)=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2026,i,1).toLocaleString('id-ID',{month:'long'})}</option>)}</select></label><div className="filter-strip-note"><Layers3 size={15}/><span>{group?.name} · Group Consolidated · IDR</span></div></div>
    <div className="stats-grid"><StatCard title="Consolidated Revenue" value={money(preview.consolidatedRevenue)} hint={`before elimination ${money(preview.totalRevenue)}`} icon={CircleDollarSign}/><StatCard title="Consolidated Expense" value={money(preview.consolidatedExpense)} hint={`IC elimination ${money(preview.eliminations.expense)}`} icon={Scale}/><StatCard title="Consolidated Net Income" value={money(preview.consolidatedNetIncome)} hint={`pre-elim ${money(preview.preEliminationNetIncome)}`} icon={Building2}/><StatCard title="Unrealized Profit" value={money(preview.eliminations.unrealizedProfit)} hint="inventory markup elimination" icon={WandSparkles}/></div>
    <section className={`surface-card consolidation-status ${run?.status==='Posted'?'posted':run?'prepared':'draft'}`}><div><span>{run?.status==='Posted'?<CheckCircle2 size={19}/>:run?<RefreshCw size={19}/>:<LockKeyhole size={19}/>}</span><div><strong>{run?`Consolidation ${run.status}`:'No consolidation run yet'}</strong><small>{run?`${run.id} · Prepared ${dateTimeLabel(run.preparedAt)}${run.postedAt?` · Posted ${dateTimeLabel(run.postedAt)}`:''}`:'Prepare akan snapshot entity results dan menandai intercompany elimination sebagai Prepared.'}</small></div></div><div className="action-row">{!run&&<button className="btn btn-primary" onClick={prepare}>Prepare Consolidation</button>}{run?.status==='Prepared'&&<button className="btn btn-primary" disabled={!preview.allEntitiesClosed} onClick={()=>postConsolidation(run.id)}>Post Consolidation</button>}</div></section>
    {run?.status==='Prepared'&&!preview.allEntitiesClosed&&<div className="surface-card inventory-warning"><LockKeyhole size={18}/><div><strong>POSTING LOCKED</strong><span>Consolidation baru dapat diposting ketika seluruh legal entity sudah menutup accounting period yang sama. Switch ke masing-masing entity lalu selesaikan Closing Period.</span></div></div>}
    <SectionCard title="Entity Close & Financial Result" subtitle="Setiap legal entity mempunyai period lock dan ledger sendiri sebelum group consolidation."><DataTable rows={entityRows} columns={[{key:'code',label:'Entity'},{key:'revenueLabel',label:'Revenue'},{key:'expenseLabel',label:'Expense'},{key:'netLabel',label:'Net Income'},{key:'periodStatus',label:'Period',render:(v)=><StatusPill tone={v==='Closed'?'success':v==='Open'?'info':'danger'}>{v}</StatusPill>},{key:'blockerCount',label:'Close Blockers'},{key:'closeReady',label:'Readiness',render:(v)=><StatusPill tone={v?'success':'warning'}>{v?'Ready':'Review'}</StatusPill>}]}/></SectionCard>
    <div className="dashboard-grid"><SectionCard title="Intercompany Eliminations" subtitle="Revenue/expense, reciprocal balance, dan inventory markup." className="span-2"><DataTable rows={icRows} columns={[{key:'id',label:'IC Document'},{key:'type',label:'Type'},{key:'pair',label:'Entity Pair'},{key:'amount',label:'IC Amount',render:(v)=>money(v)},{key:'outstanding',label:'Due From / To',render:(v)=>money(v)},{key:'unrealized',label:'Unrealized',render:(v)=>money(v)},{key:'eliminationStatus',label:'Elimination',render:(v)=><StatusPill tone={v==='Eliminated'?'success':v==='Prepared'?'info':'warning'}>{v}</StatusPill>}]}/></SectionCard><SectionCard title="Elimination Bridge" subtitle="Consolidation adjustments"><div className="consolidation-bridge"><div><span>IC Revenue</span><strong>- {money(preview.eliminations.revenue)}</strong></div><div><span>IC Expense / COGS</span><strong>- {money(preview.eliminations.expense)}</strong></div><div><span>Due From</span><strong>- {money(preview.eliminations.dueFrom)}</strong></div><div><span>Due To</span><strong>- {money(preview.eliminations.dueTo)}</strong></div><div className="grand"><span>Unrealized Inventory Profit</span><strong>- {money(preview.eliminations.unrealizedProfit)}</strong></div></div></SectionCard></div>
    <SectionCard title="Consolidation Run History" subtitle="Prepared and posted snapshots are preserved for audit."><DataTable rows={rawData.consolidationRuns.filter((r)=>r.groupId===scope.groupId)} emptyText="Belum ada consolidation run." columns={[{key:'id',label:'Run'},{key:'year',label:'Year'},{key:'month',label:'Period'},{key:'status',label:'Status',render:(v)=><StatusPill tone={statusTone(v)}>{v}</StatusPill>},{key:'preparedAt',label:'Prepared',render:(v)=>dateTimeLabel(v)},{key:'postedAt',label:'Posted',render:(v)=>dateTimeLabel(v)}]}/></SectionCard>
  </>;
}
