import React, { useMemo, useState } from 'react';
import { ArrowRight, Boxes, Building2, CircleDollarSign, Handshake, Landmark, Plus, Search } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatCard from '../components/StatCard';
import StatusPill from '../components/StatusPill';
import Modal from '../components/Modal';
import AuditTimeline from '../components/AuditTimeline';
import { useERPData } from '../context/ERPDataContext';
import { dateLabel, money, number, statusTone } from '../utils/erp';

function CreateICModal({ open, onClose, data, onCreate }) {
  const entities=data.legalEntities;
  const [form,setForm]=useState({type:'SERVICE',fromEntityId:entities[0]?.id||'',toEntityId:entities[1]?.id||'',date:new Date().toISOString().slice(0,10),description:'Shared management service',amount:85000000,fromWarehouseId:'',toWarehouseId:'',sku:data.items[0]?.sku||'',qty:10,transferPrice:0,endingInventoryRatio:1});
  React.useEffect(()=>{if(!open)return; const from=entities[0]; const to=entities.find((x)=>x.id!==from?.id); const fromWh=data.warehouses.find((w)=>w.entityId===from?.id); const toWh=data.warehouses.find((w)=>w.entityId===to?.id); const item=data.items[0]; setForm({type:'SERVICE',fromEntityId:from?.id||'',toEntityId:to?.id||'',date:new Date().toISOString().slice(0,10),description:'Shared management service',amount:85000000,fromWarehouseId:fromWh?.id||'',toWarehouseId:toWh?.id||'',sku:item?.sku||'',qty:10,transferPrice:Number(item?.standardCost||0)*1.15,endingInventoryRatio:1});},[open]);
  const fromWarehouses=data.warehouses.filter((w)=>w.entityId===form.fromEntityId); const toWarehouses=data.warehouses.filter((w)=>w.entityId===form.toEntityId);
  React.useEffect(()=>{ if(form.type!=='INVENTORY')return; if(!fromWarehouses.some((w)=>w.id===form.fromWarehouseId))setForm((prev)=>({...prev,fromWarehouseId:fromWarehouses[0]?.id||''})); },[form.fromEntityId,form.type]);
  React.useEffect(()=>{ if(form.type!=='INVENTORY')return; if(!toWarehouses.some((w)=>w.id===form.toWarehouseId))setForm((prev)=>({...prev,toWarehouseId:toWarehouses[0]?.id||''})); },[form.toEntityId,form.type]);
  const item=data.items.find((x)=>x.sku===form.sku); const stock=data.inventory.find((x)=>x.warehouseId===form.fromWarehouseId&&x.sku===form.sku); const available=Math.max(0,Number(stock?.onHand||0)-Number(stock?.reserved||0)-Number(stock?.qualityHold||0)); const amount=form.type==='INVENTORY'?Number(form.qty||0)*Number(form.transferPrice||0):Number(form.amount||0); const cost=form.type==='INVENTORY'?Number(form.qty||0)*Number(stock?.avgCost||item?.standardCost||0):0;
  const invalid=form.fromEntityId===form.toEntityId||amount<=0||(form.type==='INVENTORY'&&(!form.fromWarehouseId||!form.toWarehouseId||Number(form.qty)<=0||Number(form.qty)>available));
  return <Modal open={open} onClose={onClose} title="New Intercompany Transaction" subtitle="Shared service atau inventory transfer antar legal entity dengan dual-entry posting." footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" disabled={invalid} onClick={()=>{const id=onCreate({...form,amount:Number(form.amount),qty:Number(form.qty),transferPrice:Number(form.transferPrice),endingInventoryRatio:Number(form.endingInventoryRatio)});if(id)onClose();}}>Create Draft</button></>}>
    <div className="segmented enterprise-type-switch"><button className={form.type==='SERVICE'?'active':''} onClick={()=>setForm({...form,type:'SERVICE'})}>Shared Service</button><button className={form.type==='INVENTORY'?'active':''} onClick={()=>setForm({...form,type:'INVENTORY'})}>Inventory Transfer</button></div>
    <div className="form-grid"><label className="field"><span>From Entity</span><select value={form.fromEntityId} onChange={(e)=>setForm({...form,fromEntityId:e.target.value})}>{entities.map((e)=><option key={e.id} value={e.id}>{e.code} · {e.name}</option>)}</select></label><label className="field"><span>To Entity</span><select value={form.toEntityId} onChange={(e)=>setForm({...form,toEntityId:e.target.value})}>{entities.map((e)=><option key={e.id} value={e.id}>{e.code} · {e.name}</option>)}</select></label><label className="field"><span>Transaction Date</span><input type="date" value={form.date} onChange={(e)=>setForm({...form,date:e.target.value})}/></label><label className="field"><span>Description</span><input value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label></div>
    {form.type==='SERVICE'?<label className="field"><span>Service Amount</span><input type="number" min="1" value={form.amount} onChange={(e)=>setForm({...form,amount:e.target.value})}/></label>:<><div className="form-grid"><label className="field"><span>Source Warehouse</span><select value={form.fromWarehouseId} onChange={(e)=>setForm({...form,fromWarehouseId:e.target.value})}>{fromWarehouses.map((w)=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></label><label className="field"><span>Destination Warehouse</span><select value={form.toWarehouseId} onChange={(e)=>setForm({...form,toWarehouseId:e.target.value})}>{toWarehouses.map((w)=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></label><label className="field"><span>Item</span><select value={form.sku} onChange={(e)=>setForm({...form,sku:e.target.value})}>{data.items.map((i)=><option key={i.sku} value={i.sku}>{i.sku} · {i.name}</option>)}</select></label><label className="field"><span>Qty · available {number(available)}</span><input type="number" min="1" max={available} value={form.qty} onChange={(e)=>setForm({...form,qty:e.target.value})}/></label><label className="field"><span>Transfer Price</span><input type="number" min="1" value={form.transferPrice} onChange={(e)=>setForm({...form,transferPrice:e.target.value})}/></label><label className="field"><span>Ending Inventory Ratio</span><input type="number" min="0" max="1" step="0.05" value={form.endingInventoryRatio} onChange={(e)=>setForm({...form,endingInventoryRatio:e.target.value})}/></label></div><div className="invoice-source-preview"><div><span>Carrying Cost</span><strong>{money(stock?.avgCost||item?.standardCost||0)}</strong></div><div><span>Transfer Amount</span><strong>{money(amount)}</strong></div><div><span>Cost Amount</span><strong>{money(cost)}</strong></div><div><span>Potential Unrealized Profit</span><strong>{money(Math.max(0,amount-cost)*Number(form.endingInventoryRatio||0))}</strong></div></div></>}
  </Modal>;
}

function SettlementModal({ open, onClose, tx, data, onSettle }) {
  const payer=data.bankAccounts.filter((x)=>x.entityId===tx?.toEntityId); const receiver=data.bankAccounts.filter((x)=>x.entityId===tx?.fromEntityId); const [form,setForm]=useState({payerBankAccountId:'',receiverBankAccountId:'',date:new Date().toISOString().slice(0,10)});
  React.useEffect(()=>{if(open)setForm({payerBankAccountId:payer[0]?.id||'',receiverBankAccountId:receiver[0]?.id||'',date:new Date().toISOString().slice(0,10)})},[open,tx?.id]);
  return <Modal open={open} onClose={onClose} title={`Settle ${tx?.id||''}`} subtitle="Settlement menghapus Due To / Due From dan memindahkan saldo antar rekening entity." footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" onClick={()=>{if(onSettle(tx.id,form))onClose()}}>Post Settlement</button></>}><div className="form-grid"><label className="field"><span>Payer Bank · {data.legalEntities.find((e)=>e.id===tx?.toEntityId)?.code}</span><select value={form.payerBankAccountId} onChange={(e)=>setForm({...form,payerBankAccountId:e.target.value})}>{payer.map((b)=><option key={b.id} value={b.id}>{b.code} · {b.name} · {money(b.balance)}</option>)}</select></label><label className="field"><span>Receiver Bank · {data.legalEntities.find((e)=>e.id===tx?.fromEntityId)?.code}</span><select value={form.receiverBankAccountId} onChange={(e)=>setForm({...form,receiverBankAccountId:e.target.value})}>{receiver.map((b)=><option key={b.id} value={b.id}>{b.code} · {b.name}</option>)}</select></label><label className="field field--full"><span>Settlement Date</span><input type="date" value={form.date} onChange={(e)=>setForm({...form,date:e.target.value})}/></label></div><div className="modal-total"><span>Outstanding to Settle</span><strong>{money(tx?.outstandingAmount||0)}</strong></div></Modal>;
}

export default function IntercompanyPage(){
  const {rawData,scope,createIntercompanyTransaction,postIntercompanyTransaction,releaseIntercompanyInventory,receiveIntercompanyInventory,settleIntercompany}=useERPData();
  const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState(rawData.intercompanyTransactions[0]?.id); const [createOpen,setCreateOpen]=useState(false); const [settleOpen,setSettleOpen]=useState(false);
  const visible=useMemo(()=>rawData.intercompanyTransactions.filter((row)=>(scope.mode==='GROUP'||row.fromEntityId===scope.entityId||row.toEntityId===scope.entityId)&&`${row.id} ${row.type} ${row.description} ${row.status}`.toLowerCase().includes(query.toLowerCase())),[rawData.intercompanyTransactions,scope,query]);
  const selected=rawData.intercompanyTransactions.find((row)=>row.id===selectedId)||visible[0]||rawData.intercompanyTransactions[0];
  const entityName=(id)=>rawData.legalEntities.find((e)=>e.id===id)?.code||id; const outstanding=visible.reduce((s,r)=>s+Number(r.outstandingAmount||0),0); const unrealized=visible.reduce((s,r)=>s+Number(r.unrealizedProfit||0),0); const pendingElim=visible.filter((r)=>r.eliminationStatus!=='Eliminated'&&['Posted','Settled'].includes(r.status)).length;
  return <>
    <PageHeader eyebrow="Enterprise / Intercompany" title="Intercompany Management" description="Dual-entry related-party service, inventory transfer, due-to/due-from settlement, dan elimination tracking." actionLabel="New Intercompany" onAction={()=>setCreateOpen(true)}/>
    <div className="stats-grid"><StatCard title="IC Outstanding" value={money(outstanding)} hint="Due From = Due To" icon={CircleDollarSign}/><StatCard title="Open IC Documents" value={String(visible.filter((r)=>r.status!=='Settled').length)} hint={`${visible.length} documents in scope`} icon={Handshake}/><StatCard title="Unrealized Profit" value={money(unrealized)} hint="inventory markup to eliminate" icon={Boxes}/><StatCard title="Pending Eliminations" value={String(pendingElim)} hint="for group consolidation" icon={Building2}/></div>
    {!selected?<div className="surface-card empty-state-large">Belum ada intercompany transaction.</div>:<div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari IC, type, description..."/></label><span>{visible.length} docs</span></div><div className="document-list">{visible.map((row)=><button key={row.id} className={`document-row ${selected.id===row.id?'active':''}`} onClick={()=>setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{entityName(row.fromEntityId)} → {entityName(row.toEntityId)} · {row.type}</span><div className="document-row__meta"><small>{dateLabel(row.date)}</small><strong>{money(row.amount)}</strong></div></button>)}</div></aside>
      <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">INTERCOMPANY · {selected.type}</div><h2>{selected.id}</h2><p>{selected.description}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(selected.status)}>{selected.status}</StatusPill><div className="action-row">{selected.type==='SERVICE'&&selected.status==='Draft'&&<button className="btn btn-primary" onClick={()=>postIntercompanyTransaction(selected.id)}>Post Dual Entry</button>}{selected.type==='INVENTORY'&&selected.status==='Draft'&&<button className="btn btn-primary" onClick={()=>releaseIntercompanyInventory(selected.id)}>Release Inventory</button>}{selected.type==='INVENTORY'&&selected.status==='In Transit'&&<button className="btn btn-primary" onClick={()=>receiveIntercompanyInventory(selected.id)}>Receive at Destination</button>}{selected.status==='Posted'&&Number(selected.outstandingAmount)>0&&<button className="btn btn-primary" onClick={()=>setSettleOpen(true)}><Landmark size={14}/> Settle</button>}</div></div></div><div className="enterprise-ic-route"><div><span>FROM</span><strong>{entityName(selected.fromEntityId)}</strong><small>{rawData.legalEntities.find((e)=>e.id===selected.fromEntityId)?.name}</small></div><ArrowRight size={18}/><div><span>TO</span><strong>{entityName(selected.toEntityId)}</strong><small>{rawData.legalEntities.find((e)=>e.id===selected.toEntityId)?.name}</small></div></div></div>
      <div className="finance-mini-strip"><div><span>Transaction Amount</span><strong>{money(selected.amount)}</strong></div><div><span>Outstanding</span><strong>{money(selected.outstandingAmount)}</strong></div><div><span>Elimination</span><strong>{selected.eliminationStatus}</strong></div><div><span>Unrealized Profit</span><strong>{money(selected.unrealizedProfit||0)}</strong></div></div>
      <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Dual-Entry Traceability</h3><p>Kedua legal entity memiliki journal sendiri, namun memakai satu intercompany reference.</p></div></header><div className="enterprise-journal-pair"><div><span>Source Entity</span><strong>{entityName(selected.fromEntityId)}</strong><b>{selected.sourceJournalId||'Waiting posting'}</b><small>Due From + IC Revenue {selected.type==='INVENTORY'?'+ COGS / Inventory':''}</small></div><ArrowRight size={17}/><div><span>Destination Entity</span><strong>{entityName(selected.toEntityId)}</strong><b>{selected.destinationJournalId||'Waiting receipt/posting'}</b><small>{selected.type==='SERVICE'?'IC Expense + Due To':'Inventory + Due To'}</small></div></div>{selected.type==='INVENTORY'&&<div className="table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Qty</th><th>Unit Cost</th><th>Transfer Price</th><th>Cost</th><th>Transfer Value</th><th>Unrealized</th></tr></thead><tbody><tr><td><strong>{selected.sku}</strong></td><td>{number(selected.qty)}</td><td>{money(selected.unitCost)}</td><td>{money(selected.transferPrice)}</td><td>{money(selected.costAmount)}</td><td>{money(selected.amount)}</td><td>{money(selected.unrealizedProfit)}</td></tr></tbody></table></div>}</section><aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Elimination Control</h3><p>Prepared/Post status berasal dari consolidation run.</p></div></header><div className="related-row static"><div><span>Elimination Status</span><strong>{selected.eliminationStatus}</strong></div></div><div className="related-row static"><div><span>Settlement Journals</span><strong>{selected.settlementJournalIds?.join(', ')||'-'}</strong></div></div><div className="related-row static"><div><span>Group</span><strong>{rawData.consolidationGroups.find((g)=>g.id===selected.groupId)?.code}</strong></div></div></section><section className="surface-card document-section compact-info"><header><div><h3>Audit Trail</h3><p>Intercompany posting and settlement.</p></div></header><AuditTimeline items={selected.audit||[]}/></section></aside></div></section></div>}
    <CreateICModal open={createOpen} onClose={()=>setCreateOpen(false)} data={rawData} onCreate={(payload)=>{const id=createIntercompanyTransaction(payload);if(id)setSelectedId(id);return id;}}/>
    <SettlementModal open={settleOpen} onClose={()=>setSettleOpen(false)} tx={selected} data={rawData} onSettle={settleIntercompany}/>
  </>;
}
