import React, { useMemo, useState } from 'react';
import { CalendarDays, CircleDollarSign, Search, Store, Truck, Warehouse, Plus, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import StatusPill from '../components/StatusPill';
import Modal from '../components/Modal';
import AuditTimeline from '../components/AuditTimeline';
import { useERPData } from '../context/ERPDataContext';
import { dateLabel, money, number, statusTone } from '../utils/erp';

function CreatePOModal({open,onClose,data,onCreate}){
  const firstItem=data.items[0];
  const blank=()=>({sku:firstItem?.sku||'',qty:1,price:firstItem?.standardCost||0});
  const [form,setForm]=useState({supplierId:data.suppliers[0]?.id||'',warehouseId:data.warehouses[0]?.id||'',eta:new Date().toISOString().slice(0,10),buyer:'Procurement Buyer',notes:'',lines:[blank()]});
  React.useEffect(()=>{if(open)setForm({supplierId:data.suppliers[0]?.id||'',warehouseId:data.warehouses[0]?.id||'',eta:new Date().toISOString().slice(0,10),buyer:'Procurement Buyer',notes:'',lines:[blank()]})},[open]);
  const setLine=(i,patch)=>setForm((prev)=>({...prev,lines:prev.lines.map((row,idx)=>idx===i?{...row,...patch}:row)}));
  const total=form.lines.reduce((s,l)=>s+Number(l.qty||0)*Number(l.price||0),0);
  return <Modal open={open} onClose={onClose} title="New Purchase Order" subtitle="Direct PO untuk kebutuhan yang tidak melalui RFQ." footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" onClick={()=>{const id=onCreate(form);if(id)onClose();}}>Create Draft PO</button></>}>
    <div className="form-grid"><label className="field"><span>Supplier</span><select value={form.supplierId} onChange={(e)=>setForm({...form,supplierId:e.target.value})}>{data.suppliers.map((r)=><option key={r.id} value={r.id}>{r.code} · {r.name}</option>)}</select></label><label className="field"><span>Warehouse</span><select value={form.warehouseId} onChange={(e)=>setForm({...form,warehouseId:e.target.value})}>{data.warehouses.map((r)=><option key={r.id} value={r.id}>{r.code} · {r.name}</option>)}</select></label><label className="field"><span>ETA</span><input type="date" value={form.eta} onChange={(e)=>setForm({...form,eta:e.target.value})}/></label><label className="field"><span>Buyer</span><input value={form.buyer} onChange={(e)=>setForm({...form,buyer:e.target.value})}/></label></div>
    <div className="modal-line-head"><div><strong>PO Lines</strong><small>Harga final supplier per line.</small></div><button className="btn btn-sm" onClick={()=>setForm({...form,lines:[...form.lines,blank()]})}><Plus size={14}/> Item</button></div>
    <div className="line-editor">{form.lines.map((line,index)=>{const item=data.items.find((x)=>x.sku===line.sku);return <div className="line-editor-row" key={index}><label className="field"><span>Item</span><select value={line.sku} onChange={(e)=>{const item=data.items.find((x)=>x.sku===e.target.value);setLine(index,{sku:e.target.value,price:item?.standardCost||0})}}>{data.items.map((r)=><option key={r.sku} value={r.sku}>{r.sku} · {r.name}</option>)}</select></label><label className="field"><span>Qty</span><input type="number" min="1" value={line.qty} onChange={(e)=>setLine(index,{qty:e.target.value})}/></label><label className="field"><span>Unit Cost</span><input type="number" min="0" value={line.price} onChange={(e)=>setLine(index,{price:e.target.value})}/></label><div className="line-price"><span>UOM</span><strong>{item?.uom}</strong></div><button className="icon-btn danger-soft" disabled={form.lines.length===1} onClick={()=>setForm({...form,lines:form.lines.filter((_,i)=>i!==index)})}><Trash2 size={14}/></button></div>})}</div>
    <label className="field"><span>Notes</span><textarea rows="3" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></label><div className="modal-total"><span>PO Value before tax</span><strong>{money(total)}</strong></div>
  </Modal>;
}

export default function PurchaseOrderPage(){
  const {data,createPurchaseOrder,submitPurchaseOrder,approvePurchaseOrder,createReceivingFromPO}=useERPData();
  const navigate=useNavigate();
  const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState(data.purchaseOrders[0]?.id); const [open,setOpen]=useState(false);
  const docs=useMemo(()=>data.purchaseOrders.filter((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return `${row.id} ${s?.name||''} ${row.status} ${row.buyer}`.toLowerCase().includes(query.toLowerCase())}),[data.purchaseOrders,data.suppliers,query]);
  const selected=data.purchaseOrders.find((row)=>row.id===selectedId)||data.purchaseOrders[0];
  const supplier=data.suppliers.find((x)=>x.id===selected?.supplierId); const wh=data.warehouses.find((x)=>x.id===selected?.warehouseId);
  const total=selected?.lines.reduce((s,l)=>s+Number(l.qty)*Number(l.price||0),0)||0;
  const receivedPct=selected?.lines.length?Math.round(selected.lines.reduce((s,l)=>s+Math.min(Number(l.receivedQty||0),Number(l.qty)),0)/selected.lines.reduce((s,l)=>s+Number(l.qty),0)*100):0;
  const putAwayPct=selected?.lines.length?Math.round(selected.lines.reduce((s,l)=>s+Math.min(Number(l.putAwayQty||0),Number(l.qty)),0)/selected.lines.reduce((s,l)=>s+Number(l.qty),0)*100):0;
  const createReceiving=()=>{const id=createReceivingFromPO(selected.id);if(id)navigate('/transactions/distribution/receiving')};
  return <>
    <PageHeader eyebrow="Procure to Pay / Purchase Order" title="Purchase Order" description="Supplier commitment, approval, ETA, receiving progress, 3-way match source, dan procurement audit trail." actionLabel="Purchase Order Baru" onAction={()=>setOpen(true)}/>
    {!selected?<div className="surface-card empty-state-large">Belum ada Purchase Order.</div>:<div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari PO, supplier, buyer..."/></label><span>{docs.length} PO</span></div><div className="document-list">{docs.map((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);const value=row.lines.reduce((sum,l)=>sum+Number(l.qty)*Number(l.price||0),0);return <button key={row.id} className={`document-row ${selected.id===row.id?'active':''}`} onClick={()=>setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{s?.name}</span><div className="document-row__meta"><small>{dateLabel(row.eta)}</small><strong>{money(value)}</strong></div></button>})}</div></aside>
      <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">PO · {selected.approvalStatus}</div><h2>{selected.documentNo || selected.id}</h2><p>{supplier?.name}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(selected.status)}>{selected.status}</StatusPill><div className="action-row">{selected.status==='Draft'&&<button className="btn btn-primary" onClick={()=>submitPurchaseOrder(selected.id)}>Submit Approval</button>}{selected.status==='Pending Approval'&&<button className="btn btn-primary" onClick={()=>approvePurchaseOrder(selected.id)}>Approve PO</button>}{['Approved','Partially Received'].includes(selected.status)&&<button className="btn btn-primary" onClick={createReceiving}>Create Receiving</button>}{selected.related?.purchaseInvoice&&<button className="btn" onClick={()=>navigate('/transactions/financials/purchase-invoice')}>Open Invoice</button>}</div></div></div><div className="doc-summary-grid"><div><CalendarDays size={15}/><span>PO Date</span><strong>{dateLabel(selected.date)}</strong></div><div><Truck size={15}/><span>ETA</span><strong>{dateLabel(selected.eta)}</strong></div><div><Warehouse size={15}/><span>Warehouse</span><strong>{wh?.code}</strong></div><div><Store size={15}/><span>Payment Term</span><strong>{supplier?.paymentTerm}</strong></div></div></div>
      <div className="finance-mini-strip"><div><span>PO Value</span><strong>{money(total)}</strong></div><div><span>Received</span><strong>{receivedPct}%</strong></div><div><span>Put Away</span><strong>{putAwayPct}%</strong></div><div><span>Invoice</span><strong>{selected.related?.purchaseInvoice||'Not created'}</strong></div></div>
      <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Purchase Lines</h3><p>Ordered, received, put-away, dan invoiced quantity dalam satu view.</p></div><span>{selected.lines.length} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Item</th><th>Ordered</th><th>Received</th><th>Put Away</th><th>Invoiced</th><th>Unit Cost</th><th>Value</th></tr></thead><tbody>{selected.lines.map((line)=>{const item=data.items.find((x)=>x.sku===line.sku);return <tr key={line.sku}><td><strong>{line.sku}</strong></td><td>{item?.name}</td><td>{number(line.qty)}</td><td>{number(line.receivedQty||0)}</td><td>{number(line.putAwayQty||0)}</td><td>{number(line.invoicedQty||0)}</td><td>{money(line.price)}</td><td>{money(Number(line.qty)*Number(line.price||0))}</td></tr>})}</tbody></table></div><div className="doc-totals"><div><span>Subtotal</span><strong>{money(total)}</strong></div><div><span>Estimated PPN</span><strong>{money(Math.round(total*.11))}</strong></div><div className="grand"><span>Estimated Gross</span><strong>{money(Math.round(total*1.11))}</strong></div></div></section>
      <aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Related Documents</h3><p>PR → RFQ → PO → GRN → Invoice.</p></div></header><div className="related-row static"><div><span>Purchase Request</span><strong>{selected.related?.purchaseRequest||'-'}</strong></div></div><div className="related-row static"><div><span>RFQ</span><strong>{selected.related?.rfq||'-'}</strong></div></div><div className="related-row static"><div><span>Receiving</span><strong>{Array.isArray(selected.related?.receiving)?selected.related.receiving.join(', '):(selected.related?.receiving||'-')}</strong></div></div><div className="related-row static"><div><span>Purchase Invoice</span><strong>{selected.related?.purchaseInvoice||'-'}</strong></div></div></section><section className="surface-card document-section compact-info"><header><div><h3>Audit Trail</h3><p>PO approval & inbound history.</p></div></header><AuditTimeline items={selected.audit||[]}/></section></aside></div></section></div>}
    <CreatePOModal open={open} onClose={()=>setOpen(false)} data={data} onCreate={(payload)=>{const id=createPurchaseOrder(payload);if(id)setSelectedId(id);return id;}}/>
  </>;
}
