import React, { useMemo, useState } from 'react';
import { CalendarDays, ClipboardList, Search, UserRound, Warehouse, Plus, Trash2 } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatusPill from '../components/StatusPill';
import Modal from '../components/Modal';
import AuditTimeline from '../components/AuditTimeline';
import { useERPData } from '../context/ERPDataContext';
import { dateLabel, money, number, statusTone } from '../utils/erp';

function RequestModal({ open, onClose, data, onCreate }) {
  const blank = () => ({ sku: data.items[0]?.sku || '', qty: 1, estimatedCost: data.items[0]?.standardCost || 0 });
  const [form, setForm] = useState({ warehouseId: data.warehouses[0]?.id || '', requester: 'Inventory Planning', neededDate: new Date().toISOString().slice(0, 10), notes: '', lines: [blank()] });
  React.useEffect(() => { if (open) setForm({ warehouseId: data.warehouses[0]?.id || '', requester: 'Inventory Planning', neededDate: new Date().toISOString().slice(0, 10), notes: '', lines: [blank()] }); }, [open]);
  const setLine = (index, patch) => setForm((prev) => ({ ...prev, lines: prev.lines.map((line, i) => i === index ? { ...line, ...patch } : line) }));
  const total = form.lines.reduce((sum, line) => sum + Number(line.qty || 0) * Number(line.estimatedCost || 0), 0);
  const submit = () => { const id = onCreate(form); if (id) onClose(); };
  return <Modal open={open} onClose={onClose} title="New Purchase Request" subtitle="Demand internal sebelum sourcing supplier atau RFQ." footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" onClick={submit}>Create Draft</button></>}>
    <div className="form-grid"><label className="field"><span>Warehouse / Site</span><select value={form.warehouseId} onChange={(e)=>setForm({...form,warehouseId:e.target.value})}>{data.warehouses.map((row)=><option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label><label className="field"><span>Needed Date</span><input type="date" value={form.neededDate} onChange={(e)=>setForm({...form,neededDate:e.target.value})}/></label><label className="field field--full"><span>Requester</span><input value={form.requester} onChange={(e)=>setForm({...form,requester:e.target.value})}/></label></div>
    <div className="modal-line-head"><div><strong>Request Lines</strong><small>Estimated cost dipakai untuk approval value, bukan final supplier price.</small></div><button className="btn btn-sm" onClick={()=>setForm({...form,lines:[...form.lines,blank()]})}><Plus size={14}/> Item</button></div>
    <div className="line-editor">{form.lines.map((line,index)=>{const item=data.items.find((x)=>x.sku===line.sku);return <div className="line-editor-row" key={index}><label className="field"><span>Item</span><select value={line.sku} onChange={(e)=>{const item=data.items.find((x)=>x.sku===e.target.value);setLine(index,{sku:e.target.value,estimatedCost:item?.standardCost||0});}}>{data.items.map((row)=><option key={row.sku} value={row.sku}>{row.sku} · {row.name}</option>)}</select></label><label className="field"><span>Qty</span><input type="number" min="1" value={line.qty} onChange={(e)=>setLine(index,{qty:e.target.value})}/></label><label className="field"><span>Est. Cost</span><input type="number" min="0" value={line.estimatedCost} onChange={(e)=>setLine(index,{estimatedCost:e.target.value})}/></label><div className="line-price"><span>UOM</span><strong>{item?.uom}</strong></div><button className="icon-btn danger-soft" disabled={form.lines.length===1} onClick={()=>setForm({...form,lines:form.lines.filter((_,i)=>i!==index)})}><Trash2 size={14}/></button></div>})}</div>
    <label className="field"><span>Notes</span><textarea rows="3" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></label><div className="modal-total"><span>Estimated Request Value</span><strong>{money(total)}</strong></div>
  </Modal>;
}

function RFQModal({ open, onClose, request, data, onCreate }) {
  const [supplierId,setSupplierId]=useState(data.suppliers[0]?.id||'');
  React.useEffect(()=>{if(open)setSupplierId(data.suppliers[0]?.id||'')},[open,data.suppliers]);
  return <Modal open={open} onClose={onClose} title="Create RFQ" subtitle={`Sourcing dari ${request?.id || '-'}`} footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" disabled={!request||!supplierId} onClick={()=>{const id=onCreate({purchaseRequestId:request.id,supplierId});if(id)onClose();}}>Create RFQ</button></>}><label className="field"><span>Supplier</span><select value={supplierId} onChange={(e)=>setSupplierId(e.target.value)}>{data.suppliers.map((row)=><option key={row.id} value={row.id}>{row.code} · {row.name} · Rating {row.rating}</option>)}</select></label><div className="invoice-source-preview"><div><span>Request</span><strong>{request?.id}</strong></div><div><span>Lines</span><strong>{request?.lines.length || 0}</strong></div><div><span>Needed Date</span><strong>{dateLabel(request?.neededDate)}</strong></div><div><span>Status</span><strong>{request?.status}</strong></div></div></Modal>;
}

export default function PurchaseRequestPage(){
  const {data,createPurchaseRequest,submitPurchaseRequest,approvePurchaseRequest,createRFQFromPurchaseRequest}=useERPData();
  const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState(data.purchaseRequests[0]?.id); const [createOpen,setCreateOpen]=useState(false); const [rfqOpen,setRfqOpen]=useState(false);
  const docs=useMemo(()=>data.purchaseRequests.filter((row)=>`${row.id} ${row.requester} ${row.status}`.toLowerCase().includes(query.toLowerCase())),[data.purchaseRequests,query]);
  const selected=data.purchaseRequests.find((row)=>row.id===selectedId)||data.purchaseRequests[0];
  const estTotal=selected?.lines.reduce((s,l)=>s+Number(l.qty)*Number(l.estimatedCost||0),0)||0;
  return <>
    <PageHeader eyebrow="Procure to Pay / Purchase Request" title="Purchase Request" description="Demand internal, approval, estimated value, dan hand-off ke RFQ/sourcing." actionLabel="Purchase Request Baru" onAction={()=>setCreateOpen(true)}/>
    {!selected?<div className="surface-card empty-state-large">Belum ada Purchase Request.</div>:<div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari PR, requester, status..."/></label><span>{docs.length} request</span></div><div className="document-list">{docs.map((row)=><button key={row.id} className={`document-row ${selected.id===row.id?'active':''}`} onClick={()=>setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{row.requester}</span><div className="document-row__meta"><small>{dateLabel(row.neededDate)}</small><strong>{row.lines.length} lines</strong></div></button>)}</div></aside>
      <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">PR · {selected.approvalStatus}</div><h2>{selected.documentNo || selected.id}</h2><p>{selected.requester}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(selected.status)}>{selected.status}</StatusPill><div className="action-row">{selected.status==='Draft'&&<button className="btn btn-primary" onClick={()=>submitPurchaseRequest(selected.id)}>Submit Approval</button>}{selected.status==='Pending Approval'&&<button className="btn btn-primary" onClick={()=>approvePurchaseRequest(selected.id)}>Approve PR</button>}{selected.status==='Approved'&&<button className="btn btn-primary" onClick={()=>setRfqOpen(true)}>Create RFQ</button>}</div></div></div><div className="doc-summary-grid"><div><CalendarDays size={15}/><span>Request Date</span><strong>{dateLabel(selected.date)}</strong></div><div><CalendarDays size={15}/><span>Needed Date</span><strong>{dateLabel(selected.neededDate)}</strong></div><div><Warehouse size={15}/><span>Warehouse</span><strong>{data.warehouses.find((x)=>x.id===selected.warehouseId)?.code}</strong></div><div><UserRound size={15}/><span>Requester</span><strong>{selected.requester}</strong></div></div></div>
      <div className="finance-mini-strip"><div><span>Estimated Value</span><strong>{money(estTotal)}</strong></div><div><span>Lines</span><strong>{selected.lines.length}</strong></div><div><span>Approval</span><strong>{selected.approvalStatus}</strong></div><div><span>RFQ</span><strong>{selected.related?.rfq||'Not created'}</strong></div></div>
      <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Requested Items</h3><p>Material requirement sebelum supplier selection.</p></div><span>{selected.lines.length} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Item</th><th>Qty</th><th>UOM</th><th>Est Cost</th><th>Line Value</th></tr></thead><tbody>{selected.lines.map((line)=>{const item=data.items.find((x)=>x.sku===line.sku);return <tr key={line.sku}><td><strong>{line.sku}</strong></td><td>{item?.name}</td><td>{number(line.qty)}</td><td>{item?.uom}</td><td>{money(line.estimatedCost)}</td><td>{money(Number(line.qty)*Number(line.estimatedCost||0))}</td></tr>})}</tbody></table></div><div className="doc-totals"><div className="grand"><span>Estimated Request</span><strong>{money(estTotal)}</strong></div></div></section><aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Procurement Link</h3><p>Traceability PR ke sourcing.</p></div></header><div className="related-row static"><div><span>RFQ</span><strong>{selected.related?.rfq||'-'}</strong></div></div><div className="related-row static"><div><span>Purchase Order</span><strong>{selected.related?.purchaseOrder||'-'}</strong></div></div></section><section className="surface-card document-section compact-info"><header><div><h3>Audit Trail</h3><p>Approval & sourcing history.</p></div></header><AuditTimeline items={selected.audit||[]}/></section></aside></div></section></div>}
    <RequestModal open={createOpen} onClose={()=>setCreateOpen(false)} data={data} onCreate={(payload)=>{const id=createPurchaseRequest(payload);if(id)setSelectedId(id);return id;}}/>
    <RFQModal open={rfqOpen} onClose={()=>setRfqOpen(false)} request={selected} data={data} onCreate={(payload)=>createRFQFromPurchaseRequest(payload)}/>
  </>;
}
