import React, { useMemo, useState } from 'react';
import { CalendarDays, CircleDollarSign, FileCheck2, Search, Store, WalletCards } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatusPill from '../components/StatusPill';
import Modal from '../components/Modal';
import AuditTimeline from '../components/AuditTimeline';
import { useERPData } from '../context/ERPDataContext';
import { dateLabel, money, number, statusTone } from '../utils/erp';

function CreateInvoiceModal({open,onClose,data,onCreate}){
  const eligible=data.receivings.filter((grn)=>grn.status==='Put Away'&&!data.purchaseInvoices.some((inv)=>inv.receivingId===grn.id&&inv.status!=='Cancelled'));
  const [receivingId,setReceivingId]=useState(eligible[0]?.id||'');
  React.useEffect(()=>{if(open)setReceivingId(eligible[0]?.id||'')},[open,data.receivings,data.purchaseInvoices]);
  const grn=data.receivings.find((x)=>x.id===receivingId); const po=data.purchaseOrders.find((x)=>x.id===grn?.purchaseOrderId); const supplier=data.suppliers.find((x)=>x.id===grn?.supplierId);
  return <Modal open={open} onClose={onClose} title="Create Purchase Invoice" subtitle="Invoice dibuat dari GRN yang sudah Put Away agar 3-way match memakai PO + receipt + invoice." footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" disabled={!receivingId} onClick={()=>{const id=onCreate(receivingId);if(id)onClose();}}>Create Draft</button></>}>
    <label className="field"><span>Put Away Receiving</span><select value={receivingId} onChange={(e)=>setReceivingId(e.target.value)}>{eligible.length?eligible.map((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return <option key={row.id} value={row.id}>{row.id} · {row.purchaseOrderId} · {s?.name}</option>}):<option value="">Tidak ada GRN yang siap diinvoiced</option>}</select></label>
    {grn&&<div className="invoice-source-preview"><div><span>Supplier</span><strong>{supplier?.name}</strong></div><div><span>Purchase Order</span><strong>{po?.id}</strong></div><div><span>Receiving</span><strong>{grn.id}</strong></div><div><span>Match Source</span><strong>PO · GRN · Invoice</strong></div></div>}
  </Modal>;
}

export default function PurchaseInvoicePage(){
  const {data,createPurchaseInvoiceFromReceiving,postPurchaseInvoice}=useERPData();
  const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState(data.purchaseInvoices[0]?.id); const [open,setOpen]=useState(false);
  const docs=useMemo(()=>data.purchaseInvoices.filter((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return `${row.id} ${row.purchaseOrderId} ${s?.name||''} ${row.status} ${row.matchStatus}`.toLowerCase().includes(query.toLowerCase())}),[data.purchaseInvoices,data.suppliers,query]);
  const selected=data.purchaseInvoices.find((row)=>row.id===selectedId)||data.purchaseInvoices[0]; const supplier=data.suppliers.find((x)=>x.id===selected?.supplierId); const outstanding=selected?Math.max(0,Number(selected.total)-Number(selected.paidAmount||0)):0;
  return <>
    <PageHeader eyebrow="Procure to Pay / Purchase Invoice" title="Purchase Invoice & 3-Way Match" description="Vendor billing, PO/GRN/invoice matching, AP open-item creation, VAT input, dan automatic GL posting." actionLabel="Create Purchase Invoice" onAction={()=>setOpen(true)}/>
    {!selected?<div className="surface-card empty-state-large">Belum ada Purchase Invoice.</div>:<div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari invoice, supplier, PO..."/></label><span>{docs.length} invoice</span></div><div className="document-list">{docs.map((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return <button key={row.id} className={`document-row ${selected.id===row.id?'active':''}`} onClick={()=>setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{s?.name}</span><div className="document-row__meta"><small>{row.purchaseOrderId}</small><strong>{money(row.total)}</strong></div></button>})}</div></aside>
      <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">PINV · {selected.postingStatus} · {selected.currency}</div><h2>{selected.documentNo || selected.id}</h2><p>{supplier?.name}</p></div><div className="document-hero-actions"><StatusPill tone={selected.matchStatus==='Matched'?'success':'danger'}>{selected.matchStatus}</StatusPill><div className="action-row">{selected.postingStatus!=='Posted'&&<button className="btn btn-primary" disabled={selected.matchStatus!=='Matched'} onClick={()=>postPurchaseInvoice(selected.id)}>Post Invoice</button>}</div></div></div><div className="doc-summary-grid"><div><CalendarDays size={15}/><span>Invoice Date</span><strong>{dateLabel(selected.date)}</strong></div><div><CalendarDays size={15}/><span>Due Date</span><strong>{dateLabel(selected.dueDate)}</strong></div><div><Store size={15}/><span>Purchase Order</span><strong>{selected.purchaseOrderId}</strong></div><div><CircleDollarSign size={15}/><span>Invoice Total</span><strong>{money(selected.total)}</strong></div></div></div>
      <div className="finance-mini-strip"><div><span>Subtotal</span><strong>{money(selected.subtotal)}</strong></div><div><span>PPN Masukan</span><strong>{money(selected.tax)}</strong></div><div><span>Outstanding</span><strong>{money(outstanding)}</strong></div><div><span>AP Item</span><strong>{selected.apItemId||'Created when posted'}</strong></div></div>
      <section className="surface-card match-banner"><FileCheck2 size={18}/><div><strong>3-Way Match Control</strong><span>Purchase Order {selected.purchaseOrderId} · Receiving {selected.receivingId} · Invoice {selected.id}</span></div><StatusPill tone={selected.matchStatus==='Matched'?'success':'danger'}>{selected.matchStatus}</StatusPill></section>
      <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Invoice Lines</h3><p>Qty berasal dari accepted receiving. Harga berasal dari Purchase Order.</p></div><span>{selected.lines.length} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Description</th><th>Qty</th><th>Unit Cost</th><th>Tax</th><th>Line Total</th></tr></thead><tbody>{selected.lines.map((line)=><tr key={`${selected.id}-${line.sku}`}><td><strong>{line.sku}</strong></td><td>{line.description}</td><td>{number(line.qty)}</td><td>{money(line.price)}</td><td>{line.taxRate}%</td><td>{money(Number(line.qty)*Number(line.price)*(1+Number(line.taxRate)/100))}</td></tr>)}</tbody></table></div><div className="doc-totals"><div><span>Subtotal</span><strong>{money(selected.subtotal)}</strong></div><div><span>VAT Input</span><strong>{money(selected.tax)}</strong></div><div className="grand"><span>Total Payable</span><strong>{money(selected.total)}</strong></div></div></section>
      <aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Financial Link</h3><p>Traceability purchasing → AP → GL.</p></div></header><div className="related-row static"><div><span>Purchase Order</span><strong>{selected.purchaseOrderId}</strong></div></div><div className="related-row static"><div><span>Receiving</span><strong>{selected.receivingId}</strong></div></div><div className="related-row static"><div><span>AP Open Item</span><strong>{selected.apItemId||'-'}</strong></div></div><div className="related-row static"><div><span>Journal</span><strong>{selected.journalId||'-'}</strong></div></div></section><section className="surface-card document-section compact-info"><header><div><h3>Invoice Audit</h3><p>Match & posting history.</p></div></header><AuditTimeline items={selected.audit||[]}/></section></aside></div></section></div>}
    <CreateInvoiceModal open={open} onClose={()=>setOpen(false)} data={data} onCreate={(grnId)=>{const id=createPurchaseInvoiceFromReceiving(grnId);if(id)setSelectedId(id);return id;}}/>
  </>;
}
