import React, { useMemo, useState } from 'react';
import { BadgeDollarSign, PackageMinus, Search, ShieldCheck, Truck, WalletCards } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import Modal from '../components/Modal';
import StatusPill from '../components/StatusPill';
import AuditTimeline from '../components/AuditTimeline';
import { useERPData } from '../context/ERPDataContext';
import { dateLabel, money, number, statusTone } from '../utils/erp';

function CreateModal({ open, onClose, data, onCreate }) {
  const eligible = data.purchaseInvoices.filter((row) => row.postingStatus === 'Posted');
  const [invoiceId, setInvoiceId] = useState(eligible[0]?.id || '');
  const [reason, setReason] = useState('Supplier return due to quality / packaging issue.');
  const invoice = data.purchaseInvoices.find((row) => row.id === invoiceId);
  const buildLines = (inv) => (inv?.lines || []).map((line) => ({ sku: line.sku, qty: Math.min(1, Number(line.qty || 0)), lot: '' }));
  const [lines, setLines] = useState(buildLines(invoice));
  React.useEffect(() => { if (open) { const first = eligible[0]?.id || ''; setInvoiceId(first); setLines(buildLines(data.purchaseInvoices.find((row) => row.id === first))); } }, [open]);
  const switchInvoice = (id) => { setInvoiceId(id); setLines(buildLines(data.purchaseInvoices.find((row) => row.id === id))); };
  return <Modal open={open} onClose={onClose} title="New Purchase Return" subtitle="Return barang ke supplier dari posted purchase invoice. Posting akan mengurangi stock dan AP." wide footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" disabled={!invoiceId || !lines.some((line) => Number(line.qty) > 0)} onClick={() => { const id = onCreate({ purchaseInvoiceId: invoiceId, reason, lines }); if (id) onClose(); }}>Create Draft</button></>}>
    <div className="form-grid"><label className="field"><span>Source Purchase Invoice</span><select value={invoiceId} onChange={(e) => switchInvoice(e.target.value)}>{eligible.map((row) => <option key={row.id} value={row.id}>{row.id} · {data.suppliers.find((x) => x.id === row.supplierId)?.name}</option>)}</select></label><label className="field"><span>Supplier</span><input disabled value={data.suppliers.find((row) => row.id === invoice?.supplierId)?.name || '-'} /></label><label className="field field--full"><span>Reason</span><textarea rows="3" value={reason} onChange={(e) => setReason(e.target.value)}/></label></div>
    <div className="line-editor">{lines.map((line, index) => { const src = invoice?.lines.find((row) => row.sku === line.sku); const item = data.items.find((row) => row.sku === line.sku); return <div className="line-editor-row" key={line.sku}><div className="line-price"><span>Item</span><strong>{line.sku}</strong><small>{item?.name}</small></div><label className="field"><span>Return Qty</span><input type="number" min="0" max={src?.qty || 0} value={line.qty} onChange={(e) => setLines((prev) => prev.map((row, i) => i === index ? { ...row, qty: e.target.value } : row))}/></label><label className="field"><span>Lot</span><input value={line.lot || ''} onChange={(e) => setLines((prev) => prev.map((row, i) => i === index ? { ...row, lot: e.target.value } : row))} placeholder="optional"/></label><div className="line-price"><span>Invoice Price</span><strong>{money(src?.price || 0)}</strong></div></div>; })}</div>
  </Modal>;
}

export default function PurchaseReturnPage() {
  const { data, createPurchaseReturn, submitPurchaseReturn, approvePurchaseReturn, postPurchaseReturn } = useERPData();
  const [query, setQuery] = useState(''); const [selectedId, setSelectedId] = useState(data.purchaseReturns[0]?.id); const [open, setOpen] = useState(false);
  const docs = useMemo(() => data.purchaseReturns.filter((row) => `${row.id} ${row.documentNo} ${row.status} ${data.suppliers.find((x) => x.id === row.supplierId)?.name || ''}`.toLowerCase().includes(query.toLowerCase())), [data.purchaseReturns, data.suppliers, query]);
  const selected = data.purchaseReturns.find((row) => row.id === selectedId) || data.purchaseReturns[0]; const supplier = data.suppliers.find((row) => row.id === selected?.supplierId); const warehouse = data.warehouses.find((row) => row.id === selected?.warehouseId); const note = data.purchaseDebitNotes.find((row) => row.id === selected?.debitNoteId);
  const gross = selected?.lines.reduce((sum, line) => sum + Number(line.qty || 0) * Number(line.unitPrice || 0) * (1 + Number(line.taxRate || 0) / 100), 0) || 0;
  const blocked = selected?.status === 'Approved' && selected.lines.some((line) => { const stock = data.inventory.find((row) => row.warehouseId === selected.warehouseId && row.sku === line.sku); return Math.max(0, Number(stock?.onHand || 0) - Number(stock?.reserved || 0) - Number(stock?.qualityHold || 0)) < Number(line.qty || 0); });
  return <>
    <PageHeader eyebrow="Distribution / Reverse Logistics" title="Purchase Return" description="Governed return-to-vendor dari posted purchase invoice dengan stock issue, supplier debit note, AP reduction, VAT reversal, dan carrying-cost variance." actionLabel="Purchase Return Baru" onAction={() => setOpen(true)} />
    {!selected ? <div className="surface-card empty-state-large">Belum ada Purchase Return.</div> : <div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari return, supplier, status..."/></label><span>{docs.length} return</span></div><div className="document-list">{docs.map((row) => <button key={row.id} className={`document-row ${selected.id === row.id ? 'active' : ''}`} onClick={() => setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{data.suppliers.find((x) => x.id === row.supplierId)?.name}</span><div className="document-row__meta"><small>{dateLabel(row.date)}</small><strong>{money(row.lines.reduce((s,l)=>s+Number(l.qty||0)*Number(l.unitPrice||0),0))}</strong></div></button>)}</div></aside>
      <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">RETURN TO VENDOR · {selected.documentNo || selected.id}</div><h2>{selected.id}</h2><p>{supplier?.name} · {warehouse?.name}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(selected.status)}>{selected.status}</StatusPill><div className="action-row">{selected.status === 'Draft' && <button className="btn btn-primary" onClick={() => submitPurchaseReturn(selected.id)}><ShieldCheck size={14}/> Submit Approval</button>}{selected.status === 'Pending Approval' && <button className="btn btn-primary" onClick={() => approvePurchaseReturn(selected.id)}><ShieldCheck size={14}/> Approve</button>}{selected.status === 'Approved' && <button className="btn btn-primary" disabled={blocked} onClick={() => postPurchaseReturn(selected.id)}><Truck size={14}/> Release & Post</button>}</div></div></div><div className="doc-summary-grid"><div><PackageMinus size={15}/><span>Source Invoice</span><strong>{selected.purchaseInvoiceId}</strong></div><div><WalletCards size={15}/><span>Supplier</span><strong>{supplier?.code}</strong></div><div><Truck size={15}/><span>Warehouse</span><strong>{warehouse?.code}</strong></div><div><BadgeDollarSign size={15}/><span>Debit Value</span><strong>{money(gross)}</strong></div></div></div>
      {blocked && <div className="surface-card inventory-warning"><strong>RELEASE BLOCKED</strong><span>Available stock tidak cukup setelah reservation dan quality hold. Kurangi qty return atau selesaikan stock constraint terlebih dahulu.</span></div>}
      <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Return Lines</h3><p>Stock keluar menggunakan moving average carrying cost, sedangkan supplier debit note mengikuti invoice price.</p></div><span>{selected.lines.length} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Item</th><th>Qty</th><th>Lot</th><th>Invoice Price</th><th>Carrying Cost</th><th>Available</th></tr></thead><tbody>{selected.lines.map((line) => { const item = data.items.find((row) => row.sku === line.sku); const stock = data.inventory.find((row) => row.warehouseId === selected.warehouseId && row.sku === line.sku); const available = Math.max(0, Number(stock?.onHand || 0) - Number(stock?.reserved || 0) - Number(stock?.qualityHold || 0)); return <tr key={line.sku}><td><strong>{line.sku}</strong></td><td>{item?.name}</td><td>{number(line.qty)}</td><td>{line.lot || '-'}</td><td>{money(line.unitPrice)}</td><td>{money(stock?.avgCost || line.unitCost)}</td><td>{number(available)}</td></tr>; })}</tbody></table></div></section><aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Debit Note</h3><p>AP reduction & tax reversal.</p></div></header><div className="related-row static"><div><span>Debit Note</span><strong>{note?.id || '-'}</strong></div></div><div className="related-row static"><div><span>Gross Credit</span><strong>{note ? money(note.total) : money(gross)}</strong></div></div><div className="related-row static"><div><span>Cost Variance</span><strong>{note ? money(note.variance) : '-'}</strong></div></div></section><section className="surface-card document-section compact-info"><header><div><h3>Audit Trail</h3><p>Approval, warehouse issue, AP posting.</p></div></header><AuditTimeline items={selected.audit || []}/></section></aside></div></section></div>}
    <CreateModal open={open} onClose={() => setOpen(false)} data={data} onCreate={(payload) => { const id = createPurchaseReturn(payload); if (id) setSelectedId(id); return id; }}/>
  </>;
}
