import React, { useMemo, useState } from 'react';
import { AlertTriangle, Boxes, PackageX, Search, ShieldCheck, Siren, Unlock, Warehouse } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import Modal from '../components/Modal';
import SectionCard from '../components/SectionCard';
import StatusPill from '../components/StatusPill';
import AuditTimeline from '../components/AuditTimeline';
import { useERPData } from '../context/ERPDataContext';
import { dateTimeLabel, money, number, statusTone } from '../utils/erp';

function CreateQualityModal({ open, onClose, data, onCreate }) {
  const [form, setForm] = useState({ warehouseId: data.warehouses[0]?.id || '', sku: data.items[0]?.sku || '', lot: '', affectedQty: 1, reason: '', source: 'Internal Inspection' });
  React.useEffect(() => { if (open) setForm({ warehouseId: data.warehouses[0]?.id || '', sku: data.items[0]?.sku || '', lot: '', affectedQty: 1, reason: '', source: 'Internal Inspection' }); }, [open]);
  const lots = data.lotBalances.filter((row) => row.warehouseId === form.warehouseId && row.sku === form.sku);
  const stock = data.inventory.find((row) => row.warehouseId === form.warehouseId && row.sku === form.sku); const available = Math.max(0, Number(stock?.onHand || 0) - Number(stock?.reserved || 0) - Number(stock?.qualityHold || 0));
  return <Modal open={open} onClose={onClose} title="Open Quality Case" subtitle="Investigation case dapat dilanjutkan menjadi physical quality hold, release, scrap, atau lot recall trace." footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" disabled={!form.reason || Number(form.affectedQty) <= 0 || Number(form.affectedQty) > available} onClick={() => { const id = onCreate(form); if (id) onClose(); }}>Open Case</button></>}><div className="form-grid"><label className="field"><span>Warehouse</span><select value={form.warehouseId} onChange={(e) => setForm({ ...form, warehouseId: e.target.value, lot: '' })}>{data.warehouses.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label><label className="field"><span>Item</span><select value={form.sku} onChange={(e) => setForm({ ...form, sku: e.target.value, lot: '' })}>{data.items.map((row) => <option key={row.sku} value={row.sku}>{row.sku} · {row.name}</option>)}</select></label><label className="field"><span>Lot</span><select value={form.lot} onChange={(e) => setForm({ ...form, lot: e.target.value })}><option value="">No specific lot</option>{lots.map((row) => <option key={row.id} value={row.lot}>{row.lot} · {number(row.onHand)} on hand</option>)}</select></label><label className="field"><span>Affected Qty · Available {number(available)}</span><input type="number" min="1" max={available} value={form.affectedQty} onChange={(e) => setForm({ ...form, affectedQty: e.target.value })}/></label><label className="field"><span>Source</span><select value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })}><option>Internal Inspection</option><option>Customer Complaint</option><option>Supplier Alert</option><option>Regulatory Alert</option></select></label><label className="field field--full"><span>Reason / Finding</span><textarea rows="3" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })}/></label></div></Modal>;
}

export default function QualityControlPage() {
  const { data, createQualityCase, applyQualityHold, resolveQualityCase, startLotRecall, closeRecall } = useERPData(); const [query, setQuery] = useState(''); const [selectedId, setSelectedId] = useState(data.qualityCases[0]?.id); const [open, setOpen] = useState(false);
  const cases = useMemo(() => data.qualityCases.filter((row) => `${row.id} ${row.sku} ${row.lot} ${row.status} ${row.reason}`.toLowerCase().includes(query.toLowerCase())), [data.qualityCases, query]); const selected = data.qualityCases.find((row) => row.id === selectedId) || data.qualityCases[0]; const stock = data.inventory.find((row) => row.warehouseId === selected?.warehouseId && row.sku === selected?.sku); const lot = data.lotBalances.find((row) => row.warehouseId === selected?.warehouseId && row.sku === selected?.sku && row.lot === selected?.lot); const item = data.items.find((row) => row.sku === selected?.sku); const warehouse = data.warehouses.find((row) => row.id === selected?.warehouseId); const recall = data.recallCases.find((row) => row.id === selected?.recallId);
  const totalHold = data.inventory.reduce((sum, row) => sum + Number(row.qualityHold || 0), 0); const openCases = data.qualityCases.filter((row) => ['Monitoring','Hold','Open'].includes(row.status)).length; const activeRecalls = data.recallCases.filter((row) => ['Active','Monitoring'].includes(row.status)).length;
  return <>
    <PageHeader eyebrow="Warehouse / Quality & Traceability" title="Quality Control & Lot Recall" description="Quality hold mengurangi available stock tanpa mengubah on-hand, lalu disposition Release/Scrap menjaga inventory ledger dan GL. Lot recall menelusuri downstream shipment." actionLabel="Quality Case Baru" onAction={() => setOpen(true)} />
    <div className="stats-grid"><div className="surface-card stat-card"><div className="stat-card__top"><span>Open Quality Cases</span><ShieldCheck size={18}/></div><strong>{openCases}</strong><small>monitoring / hold</small></div><div className="surface-card stat-card"><div className="stat-card__top"><span>Quality Hold Qty</span><PackageX size={18}/></div><strong>{number(totalHold)}</strong><small>excluded from available</small></div><div className="surface-card stat-card"><div className="stat-card__top"><span>Active Recall</span><Siren size={18}/></div><strong>{activeRecalls}</strong><small>trace / containment</small></div></div>
    {!selected ? <div className="surface-card empty-state-large">Belum ada Quality Case.</div> : <div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari lot, SKU, status..."/></label><span>{cases.length} case</span></div><div className="document-list">{cases.map((row) => <button key={row.id} className={`document-row ${selected.id === row.id ? 'active' : ''}`} onClick={() => setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{row.sku} · {row.lot || 'No lot'}</span><div className="document-row__meta"><small>{row.source}</small><strong>{number(row.affectedQty)} qty</strong></div></button>)}</div></aside>
      <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">QUALITY CASE · {selected.source}</div><h2>{selected.id}</h2><p>{item?.name} · {warehouse?.name}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(selected.status)}>{selected.status}</StatusPill><div className="action-row">{!selected.holdApplied && ['Monitoring','Open'].includes(selected.status) && <button className="btn btn-primary" onClick={() => applyQualityHold(selected.id)}><AlertTriangle size={14}/> Apply Hold</button>}{selected.status === 'Hold' && <><button className="btn" onClick={() => resolveQualityCase(selected.id, 'Release')}><Unlock size={14}/> Release</button><button className="btn btn-primary" onClick={() => resolveQualityCase(selected.id, 'Scrap')}><PackageX size={14}/> Scrap</button></>}{!selected.recallId && <button className="btn" onClick={() => startLotRecall(selected.id)}><Siren size={14}/> Start Recall Trace</button>}</div></div></div><div className="doc-summary-grid"><div><Boxes size={15}/><span>Affected Qty</span><strong>{number(selected.affectedQty)}</strong></div><div><Warehouse size={15}/><span>On Hand</span><strong>{number(stock?.onHand || 0)}</strong></div><div><AlertTriangle size={15}/><span>Quality Hold</span><strong>{number(stock?.qualityHold || 0)}</strong></div><div><Siren size={15}/><span>Recall</span><strong>{selected.recallId || '-'}</strong></div></div></div>
      <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Containment & Disposition</h3><p>{selected.reason}</p></div><span>{selected.lot || 'No lot'}</span></header><div className="v9-quality-grid"><div><span>SKU</span><strong>{selected.sku}</strong></div><div><span>Lot Balance</span><strong>{number(lot?.onHand || 0)}</strong></div><div><span>Lot Hold</span><strong>{number(lot?.holdQty || 0)}</strong></div><div><span>Unit Cost</span><strong>{money(stock?.avgCost || item?.standardCost || 0)}</strong></div><div><span>Exposure Value</span><strong>{money(Number(selected.affectedQty || 0) * Number(stock?.avgCost || item?.standardCost || 0))}</strong></div><div><span>Disposition</span><strong>{selected.disposition}</strong></div></div></section><aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Audit Trail</h3><p>Investigation, hold, disposition.</p></div></header><AuditTimeline items={selected.audit || []}/></section></aside></div></section></div>}
    <SectionCard title="Lot Recall & Downstream Trace" subtitle="Recall case menghubungkan quality finding ke shipment, sales order, dan customer yang menerima lot terkait."><div className="table-wrap"><table className="data-table"><thead><tr><th>Recall</th><th>Quality Case</th><th>SKU / Lot</th><th>Status</th><th>Downstream Shipments</th><th>Exposure Qty</th><th>Action</th></tr></thead><tbody>{data.recallCases.map((row) => <tr key={row.id}><td><strong>{row.id}</strong></td><td>{row.qualityCaseId}</td><td>{row.sku} · {row.lot || '-'}</td><td><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></td><td>{(row.affectedShipments || []).map((x) => x.shipmentId).join(', ') || '-'}</td><td>{number((row.affectedShipments || []).reduce((sum, x) => sum + Number(x.qty || 0), 0))}</td><td>{['Active','Monitoring'].includes(row.status) ? <button className="btn btn-sm" onClick={() => closeRecall(row.id)}>Close Trace</button> : '-'}</td></tr>)}</tbody></table></div></SectionCard>
    <CreateQualityModal open={open} onClose={() => setOpen(false)} data={data} onCreate={(payload) => { const id = createQualityCase(payload); if (id) setSelectedId(id); return id; }}/>
  </>;
}
