import React, { useMemo, useState } from 'react';
import { Boxes, CalendarDays, PackageCheck, Search, Store, Warehouse } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatusPill from '../components/StatusPill';
import Modal from '../components/Modal';
import AuditTimeline from '../components/AuditTimeline';
import { useERPData } from '../context/ERPDataContext';
import { dateLabel, number, statusTone } from '../utils/erp';

function CreateReceivingModal({open,onClose,data,onCreate}){
  const eligible=data.purchaseOrders.filter((po)=>['Approved','Partially Received'].includes(po.status) && po.lines.some((l)=>Number(l.receivedQty||0)<Number(l.qty)));
  const [poId,setPoId]=useState(eligible[0]?.id||'');
  React.useEffect(()=>{if(open)setPoId(eligible[0]?.id||'')},[open,data.purchaseOrders]);
  const po=data.purchaseOrders.find((x)=>x.id===poId); const supplier=data.suppliers.find((x)=>x.id===po?.supplierId);
  return <Modal open={open} onClose={onClose} title="Create Goods Receiving" subtitle="Membuat inbound receipt dari remaining quantity Purchase Order." footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" disabled={!poId} onClick={()=>{const id=onCreate(poId);if(id)onClose();}}>Create GRN Draft</button></>}>
    <label className="field"><span>Approved / Partial Purchase Order</span><select value={poId} onChange={(e)=>setPoId(e.target.value)}>{eligible.length?eligible.map((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return <option key={row.id} value={row.id}>{row.id} · {s?.name}</option>}):<option value="">Tidak ada PO yang siap receiving</option>}</select></label>
    {po&&<div className="invoice-source-preview"><div><span>Supplier</span><strong>{supplier?.name}</strong></div><div><span>Warehouse</span><strong>{data.warehouses.find((x)=>x.id===po.warehouseId)?.name}</strong></div><div><span>ETA</span><strong>{dateLabel(po.eta)}</strong></div><div><span>Remaining Lines</span><strong>{po.lines.filter((l)=>Number(l.receivedQty||0)<Number(l.qty)).length}</strong></div></div>}
  </Modal>;
}

export default function ReceivingPage(){
  const {data,createReceivingFromPO,updateReceivingLine,postReceiving,putAwayReceiving}=useERPData();
  const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState(data.receivings[0]?.id); const [open,setOpen]=useState(false);
  const docs=useMemo(()=>data.receivings.filter((row)=>{const po=data.purchaseOrders.find((x)=>x.id===row.purchaseOrderId);const s=data.suppliers.find((x)=>x.id===row.supplierId);return `${row.id} ${row.purchaseOrderId} ${s?.name||''} ${row.status}`.toLowerCase().includes(query.toLowerCase())}),[data.receivings,data.purchaseOrders,data.suppliers,query]);
  const selected=data.receivings.find((row)=>row.id===selectedId)||data.receivings[0]; const po=data.purchaseOrders.find((x)=>x.id===selected?.purchaseOrderId); const supplier=data.suppliers.find((x)=>x.id===selected?.supplierId); const wh=data.warehouses.find((x)=>x.id===selected?.warehouseId);
  const putAwayLocations=(data.warehouseLocations||[]).filter((row)=>row.warehouseId===selected?.warehouseId && row.status==='Active' && row.type!=='Inbound').sort((a,b)=>Number(a.pickPriority||999)-Number(b.pickPriority||999));
  const totalAccepted=selected?.lines.reduce((s,l)=>s+Number(l.acceptedQty||0),0)||0; const totalRejected=selected?.lines.reduce((s,l)=>s+Number(l.rejectedQty||0),0)||0;
  return <>
    <PageHeader eyebrow="Procure to Pay / Receiving" title="Goods Receiving & Put Away" description="Inbound staging, accepted/rejected quantity, lot/location, receiving posting, dan put-away ke available stock." actionLabel="Create Receiving" onAction={()=>setOpen(true)}/>
    {!selected?<div className="surface-card empty-state-large">Belum ada Goods Receiving.</div>:<div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari GRN, PO, supplier..."/></label><span>{docs.length} GRN</span></div><div className="document-list">{docs.map((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return <button key={row.id} className={`document-row ${selected.id===row.id?'active':''}`} onClick={()=>setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{s?.name}</span><div className="document-row__meta"><small>{row.purchaseOrderId}</small><strong>{dateLabel(row.date)}</strong></div></button>})}</div></aside>
      <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">GRN · INBOUND</div><h2>{selected.documentNo || selected.id}</h2><p>{supplier?.name}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(selected.status)}>{selected.status}</StatusPill><div className="action-row">{selected.status==='Draft'&&<button className="btn btn-primary" onClick={()=>postReceiving(selected.id)}>Post Receiving</button>}{selected.status==='Received'&&<button className="btn btn-primary" onClick={()=>putAwayReceiving(selected.id)}>Complete Put Away</button>}</div></div></div><div className="doc-summary-grid"><div><CalendarDays size={15}/><span>Receipt Date</span><strong>{dateLabel(selected.date)}</strong></div><div><Store size={15}/><span>Purchase Order</span><strong>{selected.purchaseOrderId}</strong></div><div><Warehouse size={15}/><span>Warehouse</span><strong>{wh?.code}</strong></div><div><PackageCheck size={15}/><span>Received By</span><strong>{selected.receivedBy}</strong></div></div></div>
      <div className="finance-mini-strip"><div><span>Accepted Qty</span><strong>{number(totalAccepted)}</strong></div><div><span>Rejected Qty</span><strong>{number(totalRejected)}</strong></div><div><span>Staging</span><strong>{selected.status==='Received'?'Inbound stock':'-'}</strong></div><div><span>Availability</span><strong>{selected.status==='Put Away'?'On-hand available':'Not yet available'}</strong></div></div>
      <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Receiving Lines</h3><p>Draft receiving dapat mengubah accepted qty, lot, dan put-away destination.</p></div><span>{selected.lines.length} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Item</th><th>PO Qty</th><th>Receive</th><th>Accepted</th><th>Rejected</th><th>Lot</th><th>Put Away Location</th></tr></thead><tbody>{selected.lines.map((line)=>{const item=data.items.find((x)=>x.sku===line.sku);return <tr key={line.sku}><td><strong>{line.sku}</strong></td><td>{item?.name}</td><td>{number(line.orderedQty)}</td><td>{number(line.receiveQty)}</td><td>{selected.status==='Draft'?<input className="table-input" type="number" min="0" max={line.receiveQty} value={line.acceptedQty} onChange={(e)=>updateReceivingLine(selected.id,line.sku,{acceptedQty:e.target.value})}/>:number(line.acceptedQty)}</td><td>{number(line.rejectedQty)}</td><td>{selected.status==='Draft'?<input className="table-input" value={line.lot||''} onChange={(e)=>updateReceivingLine(selected.id,line.sku,{lot:e.target.value})}/>:line.lot}</td><td>{selected.status==='Draft'?<select className="table-input" value={line.putAwayLocation||putAwayLocations[0]?.code||''} onChange={(e)=>updateReceivingLine(selected.id,line.sku,{putAwayLocation:e.target.value})}>{putAwayLocations.length?putAwayLocations.map((loc)=><option key={loc.id} value={loc.code}>{loc.code} · {loc.zone}</option>):<option value={line.putAwayLocation||''}>{line.putAwayLocation||'No active storage location'}</option>}</select>:line.putAwayLocation}</td></tr>})}</tbody></table></div></section>
      <aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Inbound Control</h3><p>Receiving tidak langsung menjadi available stock.</p></div></header><div className="related-row static"><div><span>Purchase Order</span><strong>{po?.id}</strong></div></div><div className="related-row static"><div><span>Supplier</span><strong>{supplier?.code}</strong></div></div><div className="related-row static"><div><span>Staging Location</span><strong>{selected.lines[0]?.location||'-'}</strong></div></div><div className="related-row static"><div><span>Put Away At</span><strong>{selected.putAwayAt?new Date(selected.putAwayAt).toLocaleString('id-ID'):'-'}</strong></div></div></section><section className="surface-card document-section compact-info"><header><div><h3>Audit Trail</h3><p>Receipt & put-away history.</p></div></header><AuditTimeline items={selected.audit||[]}/></section></aside></div></section></div>}
    <CreateReceivingModal open={open} onClose={()=>setOpen(false)} data={data} onCreate={(poId)=>{const id=createReceivingFromPO(poId);if(id)setSelectedId(id);return id;}}/>
  </>;
}
