import React, { useMemo, useState } from 'react';
import { ArrowRight, Boxes, PackageSearch, Search, Sparkles, Warehouse } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import Modal from '../components/Modal';
import StatusPill from '../components/StatusPill';
import AuditTimeline from '../components/AuditTimeline';
import { useERPData } from '../context/ERPDataContext';
import { dateLabel, number, statusTone } from '../utils/erp';

function GenerateModal({ open, onClose, data, onGenerate }) {
  const [toWarehouseId, setTo] = useState(data.warehouses[0]?.id || ''); const [fromWarehouseId, setFrom] = useState('AUTO');
  React.useEffect(() => { if (open) { setTo(data.warehouses[0]?.id || ''); setFrom('AUTO'); } }, [open]);
  const destination = data.warehouses.find((row) => row.id === toWarehouseId); const sources = data.warehouses.filter((row) => row.entityId === destination?.entityId && row.id !== destination?.id);
  return <Modal open={open} onClose={onClose} title="Generate Replenishment Plan" subtitle="Sistem membaca projected available, reorder point, max stock, inbound, dan excess stock pada source warehouse." footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" onClick={() => { const id = onGenerate({ toWarehouseId, fromWarehouseId: fromWarehouseId === 'AUTO' ? null : fromWarehouseId }); if (id) onClose(); }}>Generate Plan</button></>}><div className="form-grid"><label className="field"><span>Destination Warehouse</span><select value={toWarehouseId} onChange={(e) => { setTo(e.target.value); setFrom('AUTO'); }}>{data.warehouses.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label><label className="field"><span>Source Strategy</span><select value={fromWarehouseId} onChange={(e) => setFrom(e.target.value)}><option value="AUTO">Auto · Best Excess Stock</option>{sources.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label></div><div className="inventory-count-preview"><Sparkles size={18}/><div><strong>Planning formula</strong><span>Projected = Available + Inbound + In-Transit. Suggested = Max Stock − Projected. Transfer qty dibatasi excess stock source di atas reorder point.</span></div></div></Modal>;
}

export default function ReplenishmentPage() {
  const navigate = useNavigate(); const { data, generateReplenishmentOrder, updateReplenishmentQty, convertReplenishmentToTransfer } = useERPData();
  const [query, setQuery] = useState(''); const [selectedId, setSelectedId] = useState(data.replenishmentOrders[0]?.id); const [open, setOpen] = useState(false);
  const docs = useMemo(() => data.replenishmentOrders.filter((row) => `${row.id} ${row.documentNo} ${row.status}`.toLowerCase().includes(query.toLowerCase())), [data.replenishmentOrders, query]);
  const selected = data.replenishmentOrders.find((row) => row.id === selectedId) || data.replenishmentOrders[0]; const source = data.warehouses.find((row) => row.id === selected?.fromWarehouseId); const destination = data.warehouses.find((row) => row.id === selected?.toWarehouseId); const transfer = data.stockTransfers.find((row) => row.id === selected?.transferId);
  const totalSuggested = selected?.lines.reduce((sum, line) => sum + Number(line.suggestedQty || 0), 0) || 0; const totalApproved = selected?.lines.reduce((sum, line) => sum + Number(line.approvedQty || 0), 0) || 0;
  return <>
    <PageHeader eyebrow="Warehouse / Planning" title="Replenishment Planning" description="Demand-driven inter-warehouse replenishment menggunakan reorder point, max stock, inbound, in-transit, quality hold, dan protected source stock." actionLabel="Generate Plan" onAction={() => setOpen(true)} />
    {!selected ? <div className="surface-card empty-state-large">Tidak ada SKU yang membutuhkan replenishment atau plan belum dibuat.</div> : <div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari plan, warehouse, status..."/></label><span>{docs.length} plan</span></div><div className="document-list">{docs.map((row) => <button key={row.id} className={`document-row ${selected.id === row.id ? 'active' : ''}`} onClick={() => setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{data.warehouses.find((x) => x.id === row.fromWarehouseId)?.code} → {data.warehouses.find((x) => x.id === row.toWarehouseId)?.code}</span><div className="document-row__meta"><small>{dateLabel(row.date)}</small><strong>{number(row.lines.reduce((sum, line) => sum + Number(line.approvedQty || 0), 0))} qty</strong></div></button>)}</div></aside>
      <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">REPLENISHMENT · {selected.documentNo || selected.id}</div><h2>{selected.id}</h2><p>{source?.name} → {destination?.name}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(selected.status)}>{selected.status}</StatusPill><div className="action-row">{selected.status === 'Planned' && <button className="btn btn-primary" onClick={() => convertReplenishmentToTransfer(selected.id)}><ArrowRight size={14}/> Create Stock Transfer</button>}{selected.transferId && <button className="btn" onClick={() => navigate('/warehouse/stock-transfer')}><Boxes size={14}/> Open {selected.transferId}</button>}</div></div></div><div className="doc-summary-grid"><div><Warehouse size={15}/><span>Source</span><strong>{source?.code}</strong></div><div><Warehouse size={15}/><span>Destination</span><strong>{destination?.code}</strong></div><div><PackageSearch size={15}/><span>Suggested Qty</span><strong>{number(totalSuggested)}</strong></div><div><Boxes size={15}/><span>Approved Qty</span><strong>{number(totalApproved)}</strong></div></div></div>
      <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Planning Lines</h3><p>Approved quantity dapat diturunkan sebelum dibuat menjadi Stock Transfer Draft.</p></div><span>{selected.lines.length} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Item</th><th>Projected</th><th>ROP</th><th>Max Stock</th><th>Suggested</th><th>Source Available</th><th>Approved Qty</th></tr></thead><tbody>{selected.lines.map((line) => <tr key={line.sku}><td><strong>{line.sku}</strong></td><td>{data.items.find((row) => row.sku === line.sku)?.name}</td><td>{number(line.projectedQty)}</td><td>{number(line.reorderPoint)}</td><td>{number(line.maxStock)}</td><td>{number(line.suggestedQty)}</td><td>{number(line.sourceAvailable)}</td><td>{selected.status === 'Planned' ? <input className="table-input" type="number" min="0" max={Math.min(Number(line.suggestedQty || 0), Number(line.transferableQty ?? line.sourceAvailable ?? 0))} value={line.approvedQty} onChange={(e) => updateReplenishmentQty(selected.id, line.sku, e.target.value)}/> : number(line.approvedQty)}</td></tr>)}</tbody></table></div></section><aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Execution</h3><p>Replenishment tidak memindahkan stock langsung.</p></div></header><div className="related-row static"><div><span>Transfer</span><strong>{selected.transferId || 'Not created'}</strong></div></div><div className="related-row static"><div><span>Transfer Status</span><strong>{transfer?.status || '-'}</strong></div></div><div className="related-row static"><div><span>Planner</span><strong>{selected.planner}</strong></div></div></section><section className="surface-card document-section compact-info"><header><div><h3>Audit Trail</h3><p>Planning to execution trace.</p></div></header><AuditTimeline items={selected.audit || []}/></section></aside></div></section></div>}
    <GenerateModal open={open} onClose={() => setOpen(false)} data={data} onGenerate={(payload) => { const id = generateReplenishmentOrder(payload); if (id) setSelectedId(id); return id; }}/>
  </>;
}
