import React, { useMemo, useState } from 'react';
import { CalendarDays, Search, Store, Tag, UserRound } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import StatusPill from '../components/StatusPill';
import AuditTimeline from '../components/AuditTimeline';
import { useERPData } from '../context/ERPDataContext';
import { dateLabel, money, number, statusTone } from '../utils/erp';

export default function RFQPage(){
  const {data,updateRFQPrice,convertRFQToPurchaseOrder}=useERPData();
  const navigate=useNavigate();
  const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState(data.rfqs[0]?.id);
  const docs=useMemo(()=>data.rfqs.filter((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return `${row.id} ${s?.name||''} ${row.purchaseRequestId} ${row.status}`.toLowerCase().includes(query.toLowerCase())}),[data.rfqs,data.suppliers,query]);
  const selected=data.rfqs.find((row)=>row.id===selectedId)||data.rfqs[0];
  const supplier=data.suppliers.find((x)=>x.id===selected?.supplierId);
  const total=selected?.lines.reduce((s,l)=>s+Number(l.qty)*Number(l.quotedPrice||0),0)||0;
  const convert=()=>{const id=convertRFQToPurchaseOrder(selected.id);if(id)navigate('/transactions/distribution/purchase-order')};
  return <>
    <PageHeader eyebrow="Procure to Pay / RFQ" title="Request for Quotation" description="Supplier sourcing, quoted price capture, validity, dan conversion ke Purchase Order." />
    {!selected?<div className="surface-card empty-state-large">Belum ada RFQ. Buat RFQ dari Purchase Request yang approved.</div>:<div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari RFQ, supplier, PR..."/></label><span>{docs.length} RFQ</span></div><div className="document-list">{docs.map((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return <button key={row.id} className={`document-row ${selected.id===row.id?'active':''}`} onClick={()=>setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{s?.name}</span><div className="document-row__meta"><small>{row.purchaseRequestId}</small><strong>{dateLabel(row.validUntil)}</strong></div></button>})}</div></aside>
      <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">RFQ · {selected.status}</div><h2>{selected.documentNo || selected.id}</h2><p>{supplier?.name}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(selected.status)}>{selected.status}</StatusPill><div className="action-row">{['Quoted','Open'].includes(selected.status)&&<button className="btn btn-primary" onClick={convert}>Convert to PO</button>}{selected.related?.purchaseOrder&&<button className="btn" onClick={()=>navigate('/transactions/distribution/purchase-order')}>Open {selected.related.purchaseOrder}</button>}</div></div></div><div className="doc-summary-grid"><div><CalendarDays size={15}/><span>RFQ Date</span><strong>{dateLabel(selected.date)}</strong></div><div><CalendarDays size={15}/><span>Valid Until</span><strong>{dateLabel(selected.validUntil)}</strong></div><div><Store size={15}/><span>Supplier</span><strong>{supplier?.code}</strong></div><div><UserRound size={15}/><span>Buyer</span><strong>{selected.buyer}</strong></div></div></div>
      <div className="finance-mini-strip"><div><span>Quoted Value</span><strong>{money(total)}</strong></div><div><span>Supplier Rating</span><strong>{supplier?.rating||'-'}</strong></div><div><span>Lead Time</span><strong>{supplier?.leadTimeDays||0} days</strong></div><div><span>Source PR</span><strong>{selected.purchaseRequestId}</strong></div></div>
      <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Supplier Quotation</h3><p>Quoted price bisa diedit sebelum RFQ dikonversi menjadi PO.</p></div><span>{selected.lines.length} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>SKU</th><th>Item</th><th>Qty</th><th>UOM</th><th>Quoted Price</th><th>Line Value</th></tr></thead><tbody>{selected.lines.map((line)=>{const item=data.items.find((x)=>x.sku===line.sku);return <tr key={line.sku}><td><strong>{line.sku}</strong></td><td>{item?.name}</td><td>{number(line.qty)}</td><td>{item?.uom}</td><td>{['Quoted','Open'].includes(selected.status)?<input className="table-input" type="number" min="0" value={line.quotedPrice} onChange={(e)=>updateRFQPrice(selected.id,line.sku,e.target.value)}/>:money(line.quotedPrice)}</td><td>{money(Number(line.qty)*Number(line.quotedPrice||0))}</td></tr>})}</tbody></table></div><div className="doc-totals"><div className="grand"><span>Quoted Total</span><strong>{money(total)}</strong></div></div></section><aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Supplier Snapshot</h3><p>Sourcing context.</p></div></header><div className="related-row static"><div><span>Payment Term</span><strong>{supplier?.paymentTerm}</strong></div></div><div className="related-row static"><div><span>Tax ID</span><strong>{supplier?.taxId}</strong></div></div><div className="related-row static"><div><span>Lead Time</span><strong>{supplier?.leadTimeDays} days</strong></div></div><div className="related-row static"><div><span>PO</span><strong>{selected.related?.purchaseOrder||'Not converted'}</strong></div></div></section><section className="surface-card document-section compact-info"><header><div><h3>Audit Trail</h3><p>RFQ activity.</p></div></header><AuditTimeline items={selected.audit||[]}/></section></aside></div></section></div>}
  </>;
}
