import React, { useMemo, useState } from 'react';
import { CalendarDays, FileText, MapPin, Search, Truck, UserRound } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatusPill from '../components/StatusPill';
import DocumentLifecycle from '../components/DocumentLifecycle';
import { useERPData } from '../context/ERPDataContext';
import { dateTimeLabel, money, number, statusTone } from '../utils/erp';
import { useNavigate } from 'react-router-dom';

const steps=['Planning','Scheduled','In Transit','Delivered'];
const idx={Planning:0,Scheduled:1,'In Transit':2,Delivered:3};

export default function ShipmentPage(){
  const navigate=useNavigate();
  const {data,updateShipment,dispatchShipment,deliverShipment,createSalesInvoiceFromOrder}=useERPData();
  const [selectedId,setSelectedId]=useState(data.shipments[0]?.id);
  const [query,setQuery]=useState('');
  const docs=useMemo(()=>data.shipments.filter((row)=>`${row.id} ${row.deliveryOrderId} ${row.salesOrderId} ${row.status}`.toLowerCase().includes(query.toLowerCase())),[data.shipments,query]);
  const selected=data.shipments.find((row)=>row.id===selectedId)||data.shipments[0];
  if(!selected)return <><PageHeader eyebrow="Transaction / Distribution / Shipment" title="Shipment" description="Belum ada shipment. Complete loading pada Delivery Order lalu Create Shipment."/><div className="surface-card empty-state-large">Belum ada Shipment. Flow: Delivery Order → Ready to Load → Loading → Loaded → Create Shipment.</div></>;
  const order=data.salesOrders.find((row)=>row.id===selected.salesOrderId);
  const customer=data.customers.find((row)=>row.id===selected.customerId);
  const wh=data.warehouses.find((row)=>row.id===selected.warehouseId);
  const invoice=data.salesInvoices.find((row)=>row.salesOrderId===selected.salesOrderId&&row.status!=='Cancelled');
  return <>
    <PageHeader eyebrow="Transaction / Distribution / Shipment" title="Shipment" description="Dispatch lifecycle, vehicle, driver, route, physical stock issue, proof of delivery, dan traceability ke SO/DO."/>
    <div className="document-layout"><aside className="surface-card document-list-pane"><div className="document-list-head"><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari shipment..."/></label><span>{docs.length} shipment</span></div><div className="document-list">{docs.map((row)=><button key={row.id} className={`document-row ${row.id===selected.id?'active':''}`} onClick={()=>setSelectedId(row.id)}><div className="document-row__top"><strong>{row.id}</strong><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></div><span>{row.deliveryOrderId}</span><div className="document-row__meta"><small>{dateTimeLabel(row.createdAt)}</small><strong>{row.lines.reduce((s,l)=>s+Number(l.qty),0)} qty</strong></div></button>)}</div></aside>
    <section className="document-workspace"><div className="surface-card document-hero"><div className="document-hero__top"><div><div className="doc-kicker">SHP · {wh?.code} · {selected.deliveryOrderId}</div><h2>{selected.id}</h2><p>{customer?.name}</p></div><div className="document-hero-actions"><StatusPill tone={statusTone(selected.status)}>{selected.status}</StatusPill><div className="action-row">{selected.status==='Planning'&&<><button className="btn" onClick={()=>updateShipment(selected.id,{status:'Scheduled'})}>Schedule</button><button className="btn btn-primary" onClick={()=>dispatchShipment(selected.id)}>Dispatch Now</button></>}{selected.status==='Scheduled'&&<button className="btn btn-primary" onClick={()=>dispatchShipment(selected.id)}>Dispatch</button>}{selected.status==='In Transit'&&<button className="btn btn-primary" onClick={()=>deliverShipment(selected.id)}>Mark Delivered + POD</button>}{selected.status==='Delivered'&&!invoice&&<button className="btn btn-primary" onClick={()=>{createSalesInvoiceFromOrder(selected.salesOrderId);navigate('/transactions/financials/sales-invoice')}}><FileText size={15}/> Create Invoice</button>}{invoice&&<button className="btn" onClick={()=>navigate('/transactions/financials/sales-invoice')}>Open {invoice.id}</button>}</div></div></div><div className="doc-summary-grid"><div><CalendarDays size={15}/><span>Dispatched</span><strong>{dateTimeLabel(selected.dispatchedAt)}</strong></div><div><UserRound size={15}/><span>Driver</span><strong>{selected.driver}</strong></div><div><MapPin size={15}/><span>Route</span><strong>{selected.route}</strong></div><div><Truck size={15}/><span>Vehicle</span><strong>{selected.vehicle}</strong></div></div></div>
    <DocumentLifecycle steps={steps} currentIndex={idx[selected.status]??0} label={selected.status}/>
    <div className="document-content-grid"><section className="surface-card document-section"><header><div><h3>Cargo Manifest</h3><p>Stock keluar diposting saat shipment di-dispatch.</p></div><span>{selected.lines.length} lines</span></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>Description</th><th>Lot</th><th>Shipment Qty</th><th>Unit Cost</th><th>COGS</th></tr></thead><tbody>{selected.lines.map((line)=>{const item=data.items.find((x)=>x.sku===line.sku);return <tr key={line.sku}><td><strong>{line.sku}</strong></td><td>{item?.name}</td><td>{line.lot}</td><td>{number(line.qty)} {item?.uom}</td><td>{line.unitCost?money(line.unitCost):'-'}</td><td>{line.cogs?money(line.cogs):'-'}</td></tr>})}</tbody></table></div></section><aside className="document-side-stack"><section className="surface-card document-section compact-info"><header><div><h3>Dispatch Plan</h3><p>Route planning sebelum dispatch.</p></div></header><div className="inline-form"><label className="field"><span>Vehicle</span><input value={selected.vehicle||''} disabled={selected.status==='Delivered'} onChange={(e)=>updateShipment(selected.id,{vehicle:e.target.value})}/></label><label className="field"><span>Driver</span><input value={selected.driver||''} disabled={selected.status==='Delivered'} onChange={(e)=>updateShipment(selected.id,{driver:e.target.value})}/></label><label className="field"><span>Route</span><input value={selected.route||''} disabled={selected.status==='Delivered'} onChange={(e)=>updateShipment(selected.id,{route:e.target.value})}/></label></div></section><section className="surface-card document-section compact-info"><header><div><h3>Proof & Traceability</h3><p>End-to-end fulfillment.</p></div></header><div className="related-row static"><div><span>Sales Order</span><strong>{order?.id}</strong></div></div><div className="related-row static"><div><span>Delivery Order</span><strong>{selected.deliveryOrderId}</strong></div></div><div className="related-row static"><div><span>Proof of Delivery</span><strong>{selected.pod||'Waiting'}</strong></div></div><div className="related-row static"><div><span>COGS Journal</span><strong>{selected.cogsJournalId||'Posted on dispatch'}</strong></div></div><div className="related-row static"><div><span>COGS Amount</span><strong>{selected.cogsAmount?money(selected.cogsAmount):'-'}</strong></div></div></section></aside></div>
    </section></div>
  </>;
}
