import React, { useMemo, useState } from 'react';
import { Building2, CalendarDays, CircleDollarSign, Search, WalletCards } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import StatusPill from '../components/StatusPill';
import Modal from '../components/Modal';
import { useERPData } from '../context/ERPDataContext';
import { dateLabel, money, statusTone } from '../utils/erp';

function PaymentModal({open,onClose,data,onCreate}){
  const openAp=data.apOpenItems.filter((row)=>Number(row.outstanding)>0&&row.supplierId);
  const first=openAp[0];
  const [form,setForm]=useState({invoiceId:first?.billId||'',amount:first?.outstanding||0,accountId:data.bankAccounts[0]?.id||'',method:'Bank Transfer',reference:'',date:new Date().toISOString().slice(0,10)});
  React.useEffect(()=>{if(!open)return;const row=data.apOpenItems.find((x)=>Number(x.outstanding)>0&&x.supplierId);setForm({invoiceId:row?.billId||'',amount:row?.outstanding||0,accountId:data.bankAccounts[0]?.id||'',method:'Bank Transfer',reference:'',date:new Date().toISOString().slice(0,10)})},[open,data.apOpenItems,data.purchaseInvoices,data.bankAccounts]);
  const ap=data.apOpenItems.find((x)=>x.billId===form.invoiceId); const invoice=data.purchaseInvoices.find((x)=>x.id===form.invoiceId); const supplier=data.suppliers.find((x)=>x.id===(invoice?.supplierId||ap?.supplierId)); const account=data.bankAccounts.find((x)=>x.id===form.accountId);
  return <Modal open={open} onClose={onClose} title="Supplier Payment / Bank Disbursement" subtitle="Allocate payment ke AP open item dan post Dr AP / Cr Bank secara otomatis." footer={<><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-primary" disabled={!form.invoiceId||Number(form.amount)<=0} onClick={()=>{const id=onCreate({...form,amount:Number(form.amount)});if(id)onClose();}}>Post Payment</button></>}>
    <div className="form-grid"><label className="field field--full"><span>Open AP Document</span><select value={form.invoiceId} onChange={(e)=>{const row=data.apOpenItems.find((x)=>x.billId===e.target.value);setForm({...form,invoiceId:e.target.value,amount:row?.outstanding||0})}}>{openAp.length?openAp.map((row)=>{const inv=data.purchaseInvoices.find((x)=>x.id===row.billId);const sup=data.suppliers.find((x)=>x.id===(inv?.supplierId||row.supplierId));return <option key={row.id} value={row.billId}>{row.billId} · {sup?.name||row.supplier} · {money(row.outstanding)}</option>}):<option value="">Tidak ada AP terbuka yang dapat dibayar</option>}</select></label><label className="field"><span>Payment Date</span><input type="date" value={form.date} onChange={(e)=>setForm({...form,date:e.target.value})}/></label><label className="field"><span>Amount</span><input type="number" min="1" max={ap?.outstanding||0} value={form.amount} onChange={(e)=>setForm({...form,amount:e.target.value})}/></label><label className="field"><span>Bank / Cash Account</span><select value={form.accountId} onChange={(e)=>setForm({...form,accountId:e.target.value})}>{data.bankAccounts.map((row)=><option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label><label className="field"><span>Method</span><select value={form.method} onChange={(e)=>setForm({...form,method:e.target.value})}><option>Bank Transfer</option><option>Cash</option><option>Cheque</option><option>Virtual Account</option></select></label><label className="field field--full"><span>Bank Reference</span><input value={form.reference} onChange={(e)=>setForm({...form,reference:e.target.value})} placeholder="TRX / cheque / transfer reference"/></label></div>
    {ap&&<div className="invoice-source-preview"><div><span>Supplier</span><strong>{supplier?.name||ap?.supplier}</strong></div><div><span>Outstanding</span><strong>{money(ap?.outstanding)}</strong></div><div><span>Bank Balance</span><strong>{money(account?.balance)}</strong></div><div><span>Balance After</span><strong>{money(Number(account?.balance||0)-Number(form.amount||0))}</strong></div></div>}
  </Modal>;
}

export default function SupplierPaymentsPage(){
  const {data,createSupplierPayment}=useERPData(); const [open,setOpen]=useState(false); const [query,setQuery]=useState('');
  const rows=useMemo(()=>data.supplierPayments.filter((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return `${row.id} ${row.invoiceId} ${s?.name||''} ${row.reference||''}`.toLowerCase().includes(query.toLowerCase())}),[data.supplierPayments,data.suppliers,query]);
  const apOpen=data.apOpenItems.reduce((s,r)=>s+Number(r.outstanding||0),0); const paidToday=data.supplierPayments.filter((r)=>r.date===new Date().toISOString().slice(0,10)).reduce((s,r)=>s+Number(r.amount||0),0);
  return <>
    <PageHeader eyebrow="Procure to Pay / Payment" title="Supplier Payment & Bank Disbursement" description="AP settlement, bank/cash disbursement, payment allocation, dan automatic GL posting." actionLabel="Pay Supplier" onAction={()=>setOpen(true)}/>
    <div className="stats-grid"><div className="surface-card finance-kpi"><CircleDollarSign/><span>Open AP</span><strong>{money(apOpen)}</strong><small>{data.apOpenItems.filter((r)=>Number(r.outstanding)>0).length} open item</small></div><div className="surface-card finance-kpi"><WalletCards/><span>Paid Today</span><strong>{money(paidToday)}</strong><small>{data.supplierPayments.filter((r)=>r.date===new Date().toISOString().slice(0,10)).length} disbursement</small></div><div className="surface-card finance-kpi"><Building2/><span>Bank Balance</span><strong>{money(data.bankAccounts.filter((r)=>r.type==='Bank').reduce((s,r)=>s+Number(r.balance||0),0))}</strong><small>available operational funds</small></div><div className="surface-card finance-kpi"><CalendarDays/><span>Open Period</span><strong>{data.accountingPeriods.find((p)=>p.status==='Open')?.label||'-'}</strong><small>posting gate</small></div></div>
    <section className="surface-card document-section"><header><div><h3>Supplier Payment Register</h3><p>Disbursement yang sudah diposting ke AP dan bank/cash.</p></div><label className="catalog-search receipt-search"><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari payment, invoice, supplier..."/></label></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Payment</th><th>Date</th><th>Supplier</th><th>AP Document</th><th>Method</th><th>Reference</th><th>Amount</th><th>Status</th><th>Journal</th></tr></thead><tbody>{rows.map((row)=>{const s=data.suppliers.find((x)=>x.id===row.supplierId);return <tr key={row.id}><td><strong>{row.id}</strong></td><td>{dateLabel(row.date)}</td><td>{s?.name}</td><td>{row.invoiceId}</td><td>{row.method}</td><td>{row.reference||'-'}</td><td>{money(row.amount)}</td><td><StatusPill tone={statusTone(row.status)}>{row.status}</StatusPill></td><td>{row.journalId}</td></tr>})}</tbody></table></div></section>
    <PaymentModal open={open} onClose={()=>setOpen(false)} data={data} onCreate={createSupplierPayment}/>
  </>;
}
